### ISSUE TITLE
Compile error for `.` with inline table

### ISSUE THREAD

**Issue by thatismatt** [bakpakin/Fennel#102]
This Fennel:
```
(. {:a 1} :a)
```
Produces this Lua:
```
return {a = 1}.a
```
Trying to evaluate this with Lua gives: `lua: stdin:1: <eof> expected near '.'`

I think it should produce:
```
return ({a = 1}).a
```
or perhaps:
```
local _0_ = {a = 1}
return _0_.a
```

**Comment by technomancy** [comment]
Good catch. Pushed out a fix for this.
