### ISSUE TITLE
require-macros causes compile fail in project using love2d

### ISSUE THREAD

**Issue by nexustix** [bakpakin/Fennel#106]
While working on a small project that uses love2d i noticed that `(require-macro)` causes the compile to fail on code that depends on the global `love`

### Summary

Fennel treats globals like `love` as "unknown global in strict mode" when the code calls `(require macros)`

### Reproducing
I tested with a fresh `git clone` from master.

to narrow down the issue i created this minimal setup to reproduce this issue:

test.fnl
```clojure
(require-macros :macros)

(local foo (love.graphics.newFont))
```
macros.fnl
```clojure
{}
```
I compiled the file with `fennel --compile ./test.fnl`
The output i got is the following:
```
Compile error in 'love.graphics.newFont' ./test.fnl:3: unknown global in strict mode: love
stack traceback:
  [C]: in function 'error'
  /home/jamestk/git/Fennel/fennel.lua:370: in function 'assertCompile'
  /home/jamestk/git/Fennel/fennel.lua:541: in function 'symbolToExpression'
  /home/jamestk/git/Fennel/fennel.lua:815: in function 'compile1'
  /home/jamestk/git/Fennel/fennel.lua:781: in function 'compile1'
  /home/jamestk/git/Fennel/fennel.lua:954: in function 'destructure'
  /home/jamestk/git/Fennel/fennel.lua:1169: in function 'special'
  /home/jamestk/git/Fennel/fennel.lua:764: in function 'compile1'
  /home/jamestk/git/Fennel/fennel.lua:1519: in function ?
  [C]: in function 'xpcall'
  /home/jamestk/git/Fennel/fennel:73: in main chunk
  [C]: in ?
```
Obmitting `(require-macros :macros)` in `test.fnl` lets the file compile without errors.

### Workaround

After looking into some code i found that the error is generated around [line 541 in fennel.lua](https://github.com/bakpakin/Fennel/blob/master/fennel.lua#L541)

As a temporary hack i commented the lines:
```lua
    assertCompile(not isReference or isLocal or globalAllowed(parts[1]),
                  'unknown global in strict mode: ' .. parts[1], symbol)
```
After removing the lines no further errors are raised, and the program and macros work like intended.

### Comments

It might be that the failure on unknown globals is desired, but the inconsistency of it happening only when `(require-macros)` is called makes me believe that this behaviour is unintentional. 

I also found a variable called `allowedGlobals`, but iam unsure how i would add `love` to that.

**Comment by nexustix** [comment]
Addintional note:

```clojure
(local foo (love.graphics.newFont))

(require-macros :macros)
```
Also compiles without issues

**Comment by technomancy** [comment]
Thanks for the bug report. I think this should be fixed on master now; please give it a try and let us know if you have trouble!
