### ISSUE TITLE
versioned releases?

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#108]
Hey @bakpakin do you have any thoughts about starting to use version numbers so we can have an easier time referring to when a specific change in Fennel happened? I can throw up a changelog and call current master 0.1.0, and we can move on from there, or if you've got something you'd rather do I'd like to hear your thoughts.

**Comment by bakpakin** [comment]
I think that it’s probably a good idea and a change log would be good. Its been a long time coming and I think I should put a stable non-git release on luarocks as well. 

As for versioning, 0.1.0 sounds like a good place to start.

**Comment by technomancy** [comment]
I fixed the last bug I wanted for 0.1.0 in bb85b0c.

@bakpakin do you want to do the honors for the release? I don't know how to do the luarocks stuff but if it's just bumping the version number in the file I can do that. The only other thing I know we need to do is add the date of the release to the changelog and make a signed git tag.

**Comment by bakpakin** [comment]
Sure, I can do that. It’s pretty easy, I’ll get to it today if you think everything is ready.

**Comment by bakpakin** [comment]
Alright, version 0.1.0(-2) is up on luarocks, and there is a tagged release in git as well.
You can now install fennel on a system with

```
luarocks install fennel
```

Please let me know if there are issues. For some reason, when I tried using the old rockspec, fennelview.fnl broke the install, so I removed it from the rockspec.

**Comment by technomancy** [comment]
Nice; thanks!
