### ISSUE TITLE
Unexpected behaviour for `lambda` 

### ISSUE THREAD

**Issue by thatismatt** [bakpakin/Fennel#112]
The tutorial mentions this code:
```
(global print-calculation
        (lambda [x ?y z] (print (- x (* (or ?y 1) z)))))
(print-calculation 5) ; -> error: Missing argument z
```
I had expected that this would mean that you could invoke this function with only two arguments, but that isn't the case:
```
(print-calculation 5 6) ; -> error: missing argument z
```

I think it was this sentence from the tutorial that confused me:
> Note that the second argument `?y` is allowed to be omitted, but `z` is not.

Is the expected usage more like this:
```
(print-calculation 5 nil 6)
```

Is this clarification that is required in the documentation or a bug in `lambda`?

**Comment by thatismatt** [comment]
Shall I submit a PR for that documentation change?

**Comment by technomancy** [comment]
That would be great; thanks!
