### ISSUE TITLE
Arity checking mentioned in Readme and Tutorial?

### ISSUE THREAD

**Issue by uvtc** [bakpakin/Fennel#121]
The Readme says Fennel supports opt-in arity checks for `lambda` functions, and the tutorial seems to say the same, but:

~~~clojure
#!/usr/bin/env fennel

(lambda foo [a b]
  (print "a:" a)
  (print "b:" b)
  (print "Ok, done."))

(foo 1 2)
;;(foo 3) ; Ok, fails, as I'd expect, but...
(foo 4 5 6) ; Yow, this works!?
~~~

That last line works but does not appear to be fully arity-checked. That is, Fennel appears to only check if you put too *few* args, but does not complain if you supply too *many*.

**Comment by technomancy** [comment]
Good point; I've updated the docs to be more specific about the checks.
