### ISSUE TITLE
TeX

### ISSUE THREAD

**Issue by letarg0** [bakpakin/Fennel#141]
Is possible using Fennel in LuaLatex?

For example changing font or making a table from file cvs or xml

**Comment by bakpakin** [comment]
Yes, certainly! Fennel compiles down to Lua, so anywhere Lua can be used, so can Fennel. However, I'm not sure how to make LuaLatex able to understand inline fennel. 'm not very familiar with LuaLatex, but you could probably define a TeX macro like `\directfennel` that would compile fennel code to Lua and then run that with `\directlua`. I hope that this helps.

**Comment by bakpakin** [comment]
I'm closing this for now as there doesn't seem to be an an issue.
