### ISSUE TITLE
Installing using luarocks  on Windows 10 fails

### ISSUE THREAD

**Issue by ktodyruik** [bakpakin/Fennel#144]
Hi,

I just tried `luarocks install fennel` on Windows 10 / Lua for Windows v5.1.5-52. There was an error:

```
C:\>luarocks install fennel
Installing http://luarocks.org/repositories/rocks/fennel-0.2.1-2.src.rock...
rc -r -fofennel.res fennel.rc
'rc' is not recognized as an internal or external command,
operable program or batch file.

Error: Build error: Build error in wrapper binaries
```

**Comment by technomancy** [comment]
I don't use luarocks, but I don't see anywhere we call rc from our own packaging. Is it possible this is a bug in luarocks?

**Comment by technomancy** [comment]
I can't reproduce this on my machine which also does not have `rc` installed but I suspect it's not an issue with Fennel itself but other Lua infrastructure. Feel free to reopen if this is not the case.
