### ISSUE TITLE
Syntax for defining tables with both sequential and non-sequential elements

### ISSUE THREAD

**Issue by vegardsjo** [bakpakin/Fennel#145]
In Lua it's possible to define a table with both sequential and non-sequential elements like so

```lua
tbl = { key1 = 42, { key2 = 37 } }
tbl.key1 -- => 42
tbl[1] -- => 37
````
This is pretty nice when e.g. defining widget layout in [awesomewm](http:/awesomewm.org)

In Fennel:
```
{ :key1 42
  1 { :key2 37 }}
```
But this gets pretty messy for larger structures.

Is it possible to support the following (or equivalent) in Fennel?
```
{ :key1 42 { :key2 37 }}
```

**Comment by technomancy** [comment]
I consider this to be a feature; we intentionally avoid supporting mixed tables because Fennel tries to make it clearer whether you're defining a sequential table or a key/value table.

`{ :key1 42 { :key2 37 }}` doesn't make sense because it looks like a key/value table, but it has an odd number of elements. What happens when you add a fourth element; does it go back to being a regular key/value table?

I don't think it's possible to support this without sacrificing consistency.

**Comment by warreq** [comment]
I'm also using Fennel for configuring awesomewm, and the mixed tables they use for the declarative syntax had me stumped for a bit.

In general, I prefer the distinction between seqs and maps that Fennel provides, but manually changing the indices for widget layouts gets annoying pretty quick. So I made a macro that lets you build mixed tables like this at compile time.

Here's my solution, for anybody that happens across this:

`> awesome-macros.fnl`

```clojure
(local awm-macs {})

(fn awm-macs./< [...]
  (let [tbl {}]
    (var skip 0)
    (each [i v (ipairs [...])]
      (when (~= i skip)
        (let [tv (type v)]
          (match tv
                 "string" (do
                            (set skip (+ i 1))
                            (tset tbl v (. [...] skip)))
                 "table"  (table.insert tbl v)
                 _        (error (.. tv " key literal in mixed table"))))))
    tbl))

awm-macs
```

Usage (a direct translation from the wibar defined in the default `rc.lua`):
```clojure
(require-macros "awesome-macros")

(/<
 :layout wibox.layout.align.horizontal
 (/< ;; Left widgets
  :layout wibox.layout.fixed.horizontal
  mylauncher
  s.mytaglist
  s.mypromptbox)
 s.mytasklist ;; Middle widget
 (/< ;; Right widgets
  :layout wibox.layout.fixed.horizontal
  mykeyboardlayout
  (wibox.widget.systray)
  mytextclock
  s.mylayoutbox))
```

Throwing errors on non-string field names isn't technically needed, but you'd never purposefully do that in a widget definition so I treat it as an error.
