### ISSUE TITLE
Lua colon syntax

### ISSUE THREAD

**Issue by agzam** [bakpakin/Fennel#150]
I'm sorry - I'm new to Fennel and I'm not very experienced in Lua. I've been trying to find a way to use Lua's colon syntax for methods that pass self as the first parameter, e.g:

    foo:start()

in Lua is equivalent to
   
    foo.start(foo)

Of course you can always pass the first arg explicitly in Fennel code but I was wondering if there's a special syntax for that - I couldn't find a way of doing this.

**Comment by Benaiah** [comment]
The syntax is `(: foo :start)` with other arguments added after `:start`.

**Comment by agzam** [comment]
Ah... Of course. Sorry I'm an idiot. Thank you!

**Comment by agzam** [comment]
On the other hand it looks like I missed the second colon the first time I saw your reply (I was on my phone). There's no way I could figure this out by myself. Maybe I'm not so stupid after all and maybe this should be documented somewhere where newbies can find it easily?

**Comment by agzam** [comment]
Also related. How do I access `self` from the function body?

**Comment by Benaiah** [comment]
The second colon is just a shorter string syntax -
`:start` and `”start”` are identical. The self argument in Lua is simply the first argument to the function - `foo:start(bar)` is simply shorthand for `foo.start(foo, bar)`.

**Comment by technomancy** [comment]
This is documented in `reference.md` but if you think the wording there could be improved, suggestions are welcome.

> How do I access self from the function body?

To be more explicit, Fennel only has special syntax for invoking methods, not for defining them. When defining functions that are called as methods, you define them as normal functions and just call the first argument `self`.
