### ISSUE TITLE
Implementing earmuffs

### ISSUE THREAD

**Issue by gustavohmsilva** [bakpakin/Fennel#152]
Hi;

I miss the possibility to put earmuffs on global variables, like I could do in CLISP. Is that something that can be implemented for the next version?

Thanks

**Comment by bakpakin** [comment]
You can indeed put earmuffs on global variables.

```clojure
(global *a-global* 10)
(fn print-global [] (print *a-global*))

(print-global) ;; prints 10
(global *a-global* 100)
(print-global) ;; prints 100
```

Do you want something else, like using earmuffs to detect if any variable should be global?

**Comment by gustavohmsilva** [comment]
My mistake. I was following the concept that since ** are ignored in CLISP they wouldn't be necessary after the original declaration. I'm kind of new to LISP like languages and I'm trying to put together a video series for Fennel on my YT channel.

**Comment by bakpakin** [comment]
Ok, no problem, I will close this then
