### ISSUE TITLE
import-macros: alternative to require-macros with finer control

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#180]
I think we need a way to bring in macros in a more controlled manner - since require directly sets values on the current macro "namespace" (not sure what we'd call it - scope?), there should be a way to only pull in the macros we want from a target module to avoid clobbering. I would even suggest this be the default, if possible.

## Considerations
1. It might be nice to rename `require-macros` to `import-macros` since, unlike `require`, it sets things in namespace/macro scope rather than returning a value to be used.
2. It should ideally default to targeting a specific list of macros to bring in from a file, with an option to bring in all of them.

## API thoughts
Off the top of my head, something similar to [clojure's `require`](https://clojuredocs.org/clojure.core/require) would work, modified to account for the different package systems. One difference - unless we want to allow grouping/namespacing of macros onto a fake table, we could omit `:refer` and make it implied.

`(import-macros <path.to.module1> [<imports>...] ...)`

```clojure
(import-macros
  :shims-or-wat :all  ; bring in everything
  :mypkg.utils [moe larry [curly :as shemp]]) ; alias curly to shemp when importing
```

Thoughts? It's a breaking API change to default to named macro imports and require opting into full clobbering, but I think it's the sanest default behavior.

As for the name change, just a thought - I could see that not being worth the confusion, but `import` makes sense to me as a way to keep the semantics distinct.

**Comment by Benaiah** [comment]
My suggestion is to use the following syntax for `require-macros`/`import-macros`, which mirrors `require` destructuring:

```fennel
(import-macros {: macro-with-default-name :macro-with-another-name renamed-macro} :macro-file)
(macro-with-default-name ...)
(renamed-macro ...)
```
To import all macros, you could do this:

```fennel
(import-macros my-macros :macro-file)
(my-macros.macro-with-default-name ...)
```
The second use case would require a fix to the compiler allowing table-access-style calls for 
macros, but that should be relatively straightforward.

**Comment by jaawerth** [comment]
I like that destructuring syntax, but I wonder if we should be allowing the symbol-as-shorthand approach in the new `import-macros` before we allow it in destructuring in general, just to keep syntax simple and the cognitive debt low.

In other words, I like that syntax but think we should also allow
```clojure
(local {a b c} {:a 1 :b 2 :c 3})
```
to work in the same update.

**Comment by technomancy** [comment]
I think what we want to do is support destructuring for macros; the main question for me is whether we should introduce a new form for it or if it should just be a 2-arg arity of the existing `require-macros`; we can deprecate the 1-arg version. I don't want to introduce a new kind of destructuring just for macros.

**Comment by Benaiah** [comment]
@jaawerth that's slightly different than the syntax I proposed, which is identical to how locals destructuring works in the current master version of Fennel. Your example can be expressed as the following in Fennel already:

```clojure
(local {: a : b : c} {:a 1 :b 2 :c 3})
```

With this in consideration, using this same syntax for macros seems to be a more consistent approach 

I've also flipped on my preference for the name, since `import-macros` does seem to match the behavior better than `require-macros` (`import` includes a file at compile time, whereas `require` loads it at runtime). Another option would be `import-macro`, since this style could be made to work in the following example, where the macro file exports a single function instead of a table of functions:

```clojure
;; sum.fnl
(fn [...] `(+ ,...))

;; example.fnl
(import-macro sum :sum)
(print (sum 1 2 3)) ;; should print 6 
```

With multiple macros, this would look like the following:

```clojure
;; math.fnl
{:sum (fn [...] `(+ ,...)) :mult (fn [...] `(* ,...))}

;; example.fnl
(import-macro {: sum : mult} :math)
(print (mult (sum 1 2 3) (sum 4 5 6))) ;; should print 90
```

 I'd still be happy with any of the choices for the name, but `import-macro` seems like the clearest to me. My argument for it rather than `import-macros` is based on our current naming patterns - `local` can destructure into multiple assignments as well, but it isn't named `locals`.

**Comment by technomancy** [comment]
> I'd still be happy with any of the choices for the name, but import-macro seems like the clearest to me. My argument for it rather than import-macros is based on our current naming patterns - local can destructure into multiple assignments as well, but it isn't named locals.

That kinda makes sense, but on the other hand we currently have `macro` for one single macro and `macros` for multiple, and this form will usually be used to introduce multiple. I think those names bear a closer relation to this form than `local` does.

Other than the name, the examples in your comment look great, and I think that's the notation we should use for this.

**Comment by technomancy** [comment]
I was considering this for the 0.3.0 release, but the existing destructuring implementation is tied too closely to the way the compiler emits Lua; it can't be re-used for macros without some significant refactoring. Anyone's welcome to take a stab at this, but it's not going to block the release.

**Comment by jaawerth** [comment]
What do we think about making this symmetrical by adding both an `import` and `import-macros` that take the same arg signatures?

It would be nice to have some sugar for `(local foo (. (require :my-pkg) :foo)` and making `require/require-macros` and `import/import-macros` mirror one another as the simple blunt force version vs the finer-tuned approach should keep the cognitive debt to a minimum.

**Comment by jaawerth** [comment]
I did an initial pass on this in the [import-macros](https://github.com/bakpakin/Fennel/tree/import-macros) branch.

We probably shouldn't add it to the next release before putting it behind an `--expermental` flag of some sort, but it seems to work well.

```clojure
(import-macros [mymacros            :project.mymacros
               {:push append : inc} :project.othermacros])
(mymacros.foo a b c)
(mymacros.bar (d e f))
(append tbl v)
(print (inc i))
```

One caveat is that it since I didn't use the built-in destructuring (which is currently tied to emitting lua), it only supports k/v destructuring, and only one level deep.

One lucky thing: completion on macro namespaces seems to work without any changes.
