### ISSUE TITLE
document --correlate and --sourcemap

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#185]
It came up today that the `correlate` and `sourcemap` compiler options, CLI flags need documentation and such.

- [ ] Add CLI helptext for `--sourcemap` and `--correlate`
- [ ] Add docs for those options to the api.md

**Comment by technomancy** [comment]
I think maybe we should make it so `correlate` turns on automatically when `sourcemap` is disabled rather than documenting both.

**Comment by jaawerth** [comment]
Hmm, since sourcemaps can't yet be output with compiled code + used for debugging of compiled code, I'm wondering if we want it to be automatic. I can see a usecase for disabling `correlate` from the CLI as useful when compiling, as it will lead to more readable Lua output, which can be useful.

Also, disabling `sourcemap` from the CLI doesn't seem to work at present when compiling; at least when I try running `fennel --sourcemap false --compile foo.fnl` it throws an error. Are you seeing that too?

**Comment by technomancy** [comment]
Oh right; for AOT purposes it definitely makes sense to leave it in. I guess the main thing is more that we shouldn't have two flags; sourcemaps and correlation are mutually exclusive, so can just say turning on correlate turns off sourcemaps (which I think is already true?)

> fennel --sourcemap false --compile foo.fnl it throws an error. Are you seeing that too?

No, it works here.
