### ISSUE TITLE
Line numbers off on some errors (due to calling functions?)

### ISSUE THREAD

**Issue by mathias** [bakpakin/Fennel#186]
Here's my attempt to reproduce this minimally, with enough lines that it gets the line number wrong.

If you visit [this Gist](https://gist.github.com/mathias/7f221a2174ac0cef1cc956882d4aab39) you'll get it with line numbers, which will help to look at the error produced below:
```
$ fennel simple.fnl
bar
simple.fnl:6: attempt to call a table value
stack traceback:
  simple.fnl:3: in function ?
  [C]: in function 'xpcall'
  /usr/local/lib/luarocks/rocks-5.3/fennel/0.2.1-2/bin/fennel:34: in function 'dosafe'
  /usr/local/lib/luarocks/rocks-5.3/fennel/0.2.1-2/bin/fennel:130: in main chunk
  [C]: in ?
```

When I generate the Lua source with `fennel --compile simple.fnl > simple.lua`, it is possible to then spot the error on line 6 of [the Lua code](https://gist.github.com/mathias/7f221a2174ac0cef1cc956882d4aab39#file-simple-lua), but note that it does not line up with line 6 of the Fennel source in any useful way.

My local Fennel version is 0.2.1

**Comment by mathias** [comment]
I'm seeing this with `--correlate --sourcemap` added to the Fennel command, as well.

**Comment by bakpakin** [comment]
I've confirmed this happens on the latest master as well.

**Comment by mathias** [comment]
This also works with a more minimal example, which I can actually fit in my comment here:

```
(fn baz [] (each [e {:foo (fn [] "bar")}] (print e)))
(baz)
```

Which when run points at line 5:
```
$ fennel simple.fnl
simple.fnl:5: attempt to call a table value
```

Which simply doesn't exist in the original code.

**Comment by technomancy** [comment]
I think this is fixed in eb01d5b411!

**Comment by bakpakin** [comment]
Yep, I fixed this last night. I’d like to put in a quick test for it though before we close the issue.

**Comment by technomancy** [comment]
Just pushed out a test for this.
