### ISSUE TITLE
Completion should descend into tables

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#188]
Right now completion only works on top level values in globals, locals, and specials.

If you try to complete `table.co<TAB>`, you get no results; it should complete to `table.concat`.

We can take the implementation from Polywell here that knows how to descend into table fields: https://git.sr.ht/~technomancy/polywell/tree/master/polywell/commands.fnl#L215

**Comment by jaawerth** [comment]
Just took an initial swing at this in [completion-on-table-fields](https://github.com/bakpakin/Fennel/tree/completion-on-table-fields)!

It seems to be working well, but before I PR I want to add a test or two.

Also, one annoying thing I've noticed is that if you have a table like
```clojure
(local stooges {:moe {:larry {:curly "why soitenly!"}}})
```
and you type `moe.lar<tab>`, it will complete `larry` and add a space, which is annoying in the event you may want to keep adding children. I want to see if we can stop readline from adding that space when there's a match.

One option would be to just populate all matching sub-paths, so
```clojure
(local foo {:x {:y {:z 1} :yy {:z 2}}})
```
would yield
```
x.y.z
x.yy.z
```
But I suspect that would lead to annoying cutoffs and the like.

**Comment by jaawerth** [comment]
Ok, got it to stop adding the extra space, which makes table traversal easier, you no longer have to hit backspace after tab-completing a path segment.
