### ISSUE TITLE
docs conflict on tset behavior (nested setting vs k/v pairs)

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#189]
## Docs conflict
- The current docstring for `tset` shows:
  ```
  >> (doc tset)
  (tset tbl key1 val1 ... keyN valN)
    Set the fields of a table to new values. Takes 1 or more key/value pairs.
  ```
- The current [reference.md](https://github.com/bakpakin/Fennel/blob/51d184e6b5e2a958afe184d4d643b96154d331c6/reference.md#tset-set-table-field) states "You can provide multiple successive field names to perform nested sets."

## Behavior

[The tset implementation shows this behavior is deliberate in doing a nested set](https://github.com/bakpakin/Fennel/blob/687dd94b240f12a636441ebe0a92ddafe8b2fe34/fennel.lua#L1546-L1549):

```clojure
(local t {})
(tset t :a 1 :b 2)
```
Yields compiled output:
```lua
local t = {}
t["a"][1]["b"] = 2
```

As opposed to:
```lua
local t = {}
t["a"] = 1
t["b"] = 2
```

## Update docs, or change tset behavior?

Do we have an opinion on which we want to go with? Path of least resistance would be to fix the docstring, but given how using `tset` to set a nested table value breaks on `nil`, I personally find that of limited use without a `set-in`-like behavior of initializing missing table values. Still, changing the behavior now would be a breaking change.

Thoughts?

**Comment by jaawerth** [comment]
It's been pointed out that as things stand, `tset` is the mirror of `.` and I think symmetry is a good argument for leaving the behavior as-is and fixing the docstring. Interested in what the consensus is, though I'm guessing it'll be to just fix the docstring.

**Comment by technomancy** [comment]
Yeah, though the documented behavior of tset is better in isolation, I think the parallel with . makes the current behavior a better choice. My vote is to change the docstring.

**Comment by jaawerth** [comment]
In the absence of further input on this I'm just going to fix the docstring. We can always revisit later ;-)

**Comment by jaawerth** [comment]
@technomancy Just committed a fix to the docstring, but did we want to pull this out and do a quick bugfix release? I haven't tracked what's hit master since `0.3.0` hit.

**Comment by technomancy** [comment]
Thanks! We haven't had much as far as nontrivial changes on master yet, so it's a little premature for a release IMO.
