### ISSUE TITLE
global special can collide with locals when global sym is valid lua with _

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#197]
It appears that globals created with the `global` special only mangle when the symbol doesn't contain a valid lua identifier. Based on prior issues this appears to be deliberate, but it can lead to reassignment to locals in some cases.

For example, because `_` is valid in lua identifiers and skips mangling and other checks, leading to a collision that will overwrite a local:

```clojure
(local foo-bar 1)
(global foo_bar 9999)
(print foo-bar)
```
compiles to
```lua
local foo_bar = 1
foo_bar = 9999
return print(foo_bar)
```

Whereas the following code correctly causes compiler error `runtime error: expected global, found var`:

```clojure
(local foo-bar 1)
(global foo-bar 9999)
(print foo-bar)
```

A simple solution would be to enable mangling for all globals, but it appears the conditional mangling was added on purpose to allow for Lua interop. Could we add some other special form for that purpose, like `global!` to skip mangling? Or simply check the global sym against both mangled and unmangled form of locals while compiling?

**Comment by technomancy** [comment]
> Or simply check the global sym against both mangled and unmangled form of locals while compiling?

I think this is the way to go; it seems reasonable to make it an error if the mangled form already exists. It's almost always going to be unintentional, and raising it to the attention of the programmer will allow them to resolve the conflict instead of letting it go undetected.

> Could we add some other special form for that purpose, like global! to skip mangling?

We already have `set-forcibly!` for that, which should do the trick.

**Comment by jaawerth** [comment]
> > Or simply check the global sym against both mangled and unmangled form of locals while compiling?
> 
> I think this is the way to go; it seems reasonable to make it an error if the mangled form already exists. It's almost always going to be unintentional, and raising it to the attention of the programmer will allow them to resolve the conflict instead of letting it go undetected.

Makes sense. Do we care about the inverse, though? Accidental shadowing? E.g.

```
(global a_b 1)
(local a-b 99999)
(print a_b)
```
