### ISSUE TITLE
Compiler bug flattening while

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#206]
```lisp
(print :hey)

(while (let [f false] f)
  nil)
```

Results in:

```
runtime error: attempt to index field '?' (a nil value)
stack traceback:
  ./fennel.lua:767: in function 'flattenChunk'
  ./fennel.lua:801: in function ?
  [C]: in function 'xpcall'
  ./fennel:185: in main chunk
  [C]: in ?
```

Note that a compile error is being incorrectly reported as a runtime error.

**Comment by bakpakin** [comment]
I've taken a look and I think I have a fix working. Not sure what the `while` special form was doing with complex conditionals before, but it looked very wrong. I'll push a fix up soon after do a bit more testing.

**Comment by technomancy** [comment]
Awesome; just confirmed that this took care of the bug I was seeing. Nice fix!
