### ISSUE TITLE
`debug.getinfo` broken at repl

### ISSUE THREAD

**Issue by thatismatt** [bakpakin/Fennel#208]
Assuming there is a foo.fnl containing this: `{:x (fn [])}`
```
$ fennel --eval "(local foo (require :foo )) (. (debug.getinfo foo.x) :source)"
@./foo.fnl
```
Whereas at the repl:
```
Welcome to Fennel 0.3.1!
Use (doc something) to view documentation.
>> (local foo (require :foo)) (. (debug.getinfo foo.x) :source)
"@/home/matt/code/fennel/fennelview.fnl"
```
I've tracked the problem down to where the `fennel` script loads `fennelview` via `fennel.dofile`. In `dofileFennel` the `options.filename` is set, this mutation of the options table hangs around and "pollutes" any subsequently loaded fennel code. `nil`-ing out the `options.filename` after loading `fennelview` fixes the problem, but I was unsure if that was the right solution.

**Comment by technomancy** [comment]
Good catch! That's definitely not supposed to happen. Setting it to nil after loading a specific file helps in one case, but a better fix is to nil it out in `eval` after the compiler has run but before the compiled code is run.
