### ISSUE TITLE
as-> macro

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#210]
We've tossed the idea around before about adding an equivalent to [clojure's `as->`](https://clojuredocs.org/clojure.core/as-%3E) to the language. With `let` already existing, some see it as a bit redundant, but I've run into a few scenarios I think it enhances, particularly when dealing with multiple returns.

I've got an implementation of this as a macro already, but I wanted to get a discussion going before I make the PR just to get consensus and to see if there are more elegant alternatives we should consider.

### limiting or manipulating function args while threading
Arguably biggest clojure usecase is plugging different function signatures into `->`:
```clojure
(-> val (foo) (as-> y (bar x y z)))
```
Some see this as unnecessary as a built-in, and that not having it prevents excessive use of `->`. However, Fennel also has to deal with Lua's multiple returns. With `as->`, in addition to other uses, you can use it as an arity guard:

```clojure
(fn foo [] (values A B C D E F G))
 ; limit arity in threading for one function
(-> (foo) bar (as-> (x y) (baz x y)) quux)

; handling multiple arity limits and different orders
(as-> (foo) (a b c) (foo a) (arity-2-fn a b) (arity-3-fn c a b))
```

### left-right function composition, without a dedicated `comp` macro
With #209, it could be used for left-to-right function composition, dealing with any multiple returns issues while composing. Assuming for the sake of argument that we use `$&` for varargs in hashfn's:

```clojure
(local chainedfn #(-> $& foo bar (as-> (x y) (baz x y)))
```
It can also lean to cleaner handling than `let` when simply chaining operations together:
```clojure
; with 'let'
(local chain #(let [(a) (func $&)
                    (a b)   (func-1 a)
                    (a b c) (func-2 a b)]
  (func-x a x b x c)))

; with as->
(local chain #(as-> (func $&) (a b c)
                    (func-1 a)
                    (func-2 a b)
                    (func-x a x b x c))))
```

## alternatives
One alternative I've considered is adding both a `comp` macro for function composition, and an `arity` macro for wrapping functions so they're only invoked with arity `n`.

Another is a [take-values macro](https://gist.github.com/jaawerth/d6d1da04a15a9c566af4f23343625f27), which could work like a better `select` by generating bindings to only the desired subsection of the tuples. This could be used to ease composition with `->>`, and would also be used like `(bar (take-values 2 (foo)))`

**Comment by technomancy** [comment]
I'm sorry, but these examples are really difficult for me to follow.

> Arguably biggest clojure usecase is plugging different function signatures into ->

That's my main reason for being reluctant to add it--every single time I've seen it used in Clojure it makes code that's hard to read even harder to read. If you can't make it work in `->` without `as->` then it's a sign that you should reframe it as a `let`, not that you should push harder on `->`.

In Fennel I think the potential for confusion with threading macros that also bind could be even worse, because there is ambiguity about whether parens mean a call or a multi-valued binding.

> One alternative I've considered is adding both a comp macro for function composition, and an arity macro for wrapping functions so they're only invoked with arity n.

An `arity` macro is something I've definitely felt the need for already; I think it's a good idea. I haven't felt the need for `comp` oddly, but I think it would be a better addition personally.

**Comment by jaawerth** [comment]
I'm open to that. I mainly just wanted to get the conversation started about adding something to handle multiple returns when composing functions. I found `as->` a nice way to handle it but if I'm alone in that I'm totally happy going the other direction.

I already have a `comp` macro implementation, so the main thing would be deciding whether `arity` creating a function of limited arity would be enough, or if we want to make an `slice-vals` or `take-vals` that can be used in any calling context.

**Comment by Benaiah** [comment]
:+1: to an `arity` macro; that'd be very useful for me in quite a few situations.

**Comment by jaawerth** [comment]
Cool, I can PR pretty quick but would like to get some consensus on things, going to close this and open a fresh issue for vararg macros just for the sake of clarity.
