### ISSUE TITLE
include emits bad output when nested

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#214]
## Test case

Consider the following code, compiled with `--require-as-include` (which behaves the same if you change `require` to `include` and compile without that flag). It runs fine when invoked normally, but errors with `--require-as-include`:
**foo.fnl**
```clojure
(local foo [:FOO 1])
(local bar (require :bar))
(print (.. "foo: " (table.concat foo " - ")))
(print (.. "bar: " (table.concat bar " - ")))
```
**bar.fnl**
```clojure
(local bar [:BAR 2])
(each [_ v (ipairs (require :baz))]
  (table.insert bar v))
bar
```
**baz.fnl**
```clojure
[:BAZ 3]
```
The output with `--require-as-include` is:
```lua
local foo = {"FOO", 1}
local bar = bar
local _0_
do
local _0_
do
  _0_ = {"BAZ", 3}
end
  local bar = {"BAR", 2}
  for _, v in ipairs(_0_) do
    table.insert(bar, v)
  end
  _0_ = bar
end
bar = _0_
print(("foo: " .. table.concat(foo, " - ")))
return print(("bar: " .. table.concat(bar, " - ")))
```

## Solution: is include meant to be nested/repeated?

Now, even if we fix that output, if include naively inlines everything, that's going to lead to unexpected behavior, as you'll end up with two "modules" with totally separate state. So, I see two possible solutions here:

### 1. Bundle, or utilize `package.preload` (my preference)

I already have an implementation ready to PR for this. It turns `include` into a macro that inlines the code, attaches it to `package.preload`, and then invokes `require` normally. It works because `package.preload` is basically built for this purpose - one of the first searches in `package.loaders`/`package.searchers` checks for `package.preload[modulename]` and invokes it to load the module when present.

The only real downside to this approach is it won't work in Lua environments that don't have `package.preload`, but I don't know of any off the top of my head. I still think it would be better than the current behavior, which is broken, or a pure inlining behavior, as modules would always be correctly resolved.

### 2. Make include error when invoked on the same module more than once
This would break `--require-as-include` a lot, as it means you can't actually use it the same way you would require. It would really only be useful at a top-level entrypoint, pulling in a handful of 2nd-tier files. It would, however, be simpler, and could be used in any environment.

**Comment by bakpakin** [comment]
This seems to just be a bug in include. The behavior probably broke a while ago due to code churn because we had no tests for this, as this was the original use-case for include. As for inlining everything, include should cache everything and output things in the correct order, and should nest correctly. Include should also do a few other things, like properly inline Lua code as well as Fennel code.
