### ISSUE TITLE
Tables not printed correctly in repl

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#22]
```
Welcome to fennel!
>> [2]
table: 0x55b14945f880
```

It appears the metatable of `ret[1]` is not set in this case; not sure why.

**Comment by bakpakin** [comment]
This is the expected behavior. Normal tables (square brackets and curly brackets) do not set the table's metatable or any hidden values. The repl used to have a simple pretty printer which I removed for better transparency.

**Comment by technomancy** [comment]
Oh, I see. I guess I can handle this by overriding `options.print` instead if it's not supposed to work out of the box.

**Comment by bakpakin** [comment]
I recommend using something like [inspect.lua](https://github.com/kikito/inspect.lua) if you don't want to roll your own.
