### ISSUE TITLE
Store function metadata inside function upvalue

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#220]
The current implementation of metadata uses a weak table in the Fennel module as a storage location for metadata. This means that the compiler emits Lua code which must `require("fennel")`, which can cause some unexpected confusion, for instance if you move Fennel to a different module name in your source tree, you have to pass the `moduleName` option when compiling.

As shown by this snippet, it's possible to store metadata inside the function as a local and fetch it later with the `debug.getupvalue` function: https://gist.github.com/SquidDev/26ff247f55a95fd8241ef3804c684f84

We should consider using this strategy for storing metadata.

The downside is that Lua environments exist which do not expose the `debug.getupvalue` function. However, those are usually stripped-down, specialized environments where you would not necessarily expect to be doing active development that would require metadata use.

**Comment by jaawerth** [comment]
One big downside to doing this that occurred to me: you wouldn't be able to annotate external functions with metadata.

With the current weaktable approach, you can do things like annotate the Lua API (and the APIs of any environment or lua library you so choose) via parsed documentation, like I did in the experimental (and still totally undocmented) [fnldocstor](https://github.com/jaawerth/fnldocstor) I threw together.

To achieve this with upvalues, we'd need to wrap and monkeypatch every function we wanted to document this way. Though we may be able to find a way to make it work by making the metadata API and `doc` macro extensible in some fashion... maybe something to consider for the plugin + hooks system we've been talking about post-0.4.0?

**Comment by technomancy** [comment]
Yeah, I was much more concerned with this earlier before we changed it to fail gracefully when the `fennel` module was not present. With the current setup I don't think it's worth changing, especially with all the uncertainty around having it JITted away or being unable to document external functions.
