### ISSUE TITLE
Possible regression in let bindings

### ISSUE THREAD

**Issue by Olical** [bakpakin/Fennel#225]
Hey! Thanks for the wonderful language! Someone that uses my Fennel based tooling pointed out to me on twitter that the following used to work in 0.3.1 but not 0.3.2.

```clojure
(let [x (fn [] x)])
```

It'll warn that x doesn't exist at the definition of the let. Is this intended behaviour?

**Comment by technomancy** [comment]
Hi; this was actually a bug that it was allowed in 0.3.1. If you want a function that returns itself, you have to use an internal identifier, because the binding of `x` in this case cannot be established in all cases.

```
(let [x (fn x [] x)]
  ...)
```

Hope that helps.

**Comment by Olical** [comment]
Ah okay! That helps a lot! Thank you very much. I'll forward this answer onto the person that was asking about it :smile:
