### ISSUE TITLE
Weird compile error "cannot call literal value"

### ISSUE THREAD

**Issue by ndgnuh** [bakpakin/Fennel#226]
I was following [this instruction](https://gist.github.com/christoph-frick/d3949076ffc8d23e9350d3ea3b6e00cb#file-cfg-fnl) to convert my Awesomewm config to Fennel. But something weird came up:

```
error: Compile error in '(local titlebar-buttons
(gears.table.join (awful.button table: 0x41cf2a88 
1 (hashfn (cf.focus c))) (awful.button table: 0x41cf3518 
2 (hashfn (cf.kill c))) (awful.button table: 0x41cf3fa8 
3 (hashfn (cf.focus-and-mouse-resize c)))))' ./titlebars.fnl:72: cannot call literal value
```

The source code
```lisp
(fn handle-titlebars-request [c]
    ;; this one cause error
    ((local titlebar-buttons
         (gears.table.join
             (awful.button [] 1 #(cf.focus c))
             (awful.button [] 2 #(cf.kill c))
             (awful.button [] 3 #(cf.focus-and-mouse-resize c))))
     (let [titlebar-buttons (gears.table.join
             (awful.button [] 1 #(cf.focus c))
             (awful.button [] 2 #(cf.kill c))
             (awful.button [] 3 #(cf.focus-and-mouse-resize c)))]
         (print "but this one works?"))
     ;; The same to awful.titlebar
     ;; some other stuffs here
```

Also, if I get rid of `(local var` then it runs fine. Did I miss something?

**Comment by technomancy** [comment]
The error message here needs to be improved, but the problem is where you do this:

    ((local titlebar-buttons

You should have only one open-paren there. (But in general, using `let` is better style than `local` inside a function.)

**Comment by ndgnuh** [comment]
Oh my, dumbass me thought that was grouping statements.

I really need some sleep. Thank you, it's clear now.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ndgnuh** [comment]
Well, I think this issue should be closed. Thank you for the wonderful language, writing anonymous Lua function is painful
