### ISSUE TITLE
fn with method syntax

### ISSUE THREAD

**Issue by XeroOl** [bakpakin/Fennel#233]
When writing a method, I propose that `fn` should be able to accept a multisym with `:` as the first argument. For example, consider `button.fnl`:
```fennel
(local Button {})
(fn Button:onClick []
  (print self))
Button
```
This isn't currently supported in Fennel.
Running `fennel button.fnl` produces the following message:
`Compile error in 'self' button.fnl:2: unknown global in strict mode: self`

Currently, Fennel only supports `:` multisym syntax sugar for method calls, but not method function definitions.
However, I propose method definitions could supported, where the generated code would be equivalent to this:
```lua
local Button = {}
function Button:onClick()
   print(self)
end
return Button
```
Thank you very much for your time!

**Comment by technomancy** [comment]
Thanks for pointing this out. We specifically don't support this syntax, in order to avoid issues with anaphoric names. It is better to just add `self` to the arglist if that's what you want. But it should definitely be a compiler error; that was an oversight.
