### ISSUE TITLE
readline enhancements

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#236]
Planned/proposed enhancement to the CLI REPL's readline support (some in progress, others not). Feedback and additional suggestions welcome!

## In progress
- [x] __Actually document the REPL's readline support and tab completion__ via the optional readline.lua dep so people know it's there and what it can do!
- [x] __Set the application name in readline for conditional `.inputrc` directives,__ e.g.
  ```inputrc
  $if fennel
    set enable-bracketed-paste On
    set blink-matching-paren On
  $endif
  ```
  This is waiting on a [patch I submitted to readline.lua](https://gitlab.com/peterbillam/pjb_lua/-/merge_requests/1/diffs) supporting setting the libreadline application name.
- [x] __Save the REPL history if `histfile` is non-empty in the readline options__
  If we add a couple new lines to the CLI, people can simply do the following in `.fennelrc` to have a persistent rolling history:
  ```clojure
  (when package.loaded.readline
    (package.loaded.readline.set_options {:histfile "~/.fennel_repl_history"}))
  ```

## Proposed/not started
- [x] __When readline.lua fails to load, add a message to the CLI greeting msg__
  about installing readline.lua for enhanced cli support, so new users know tab completion, history, etc is there via an optional dep.

**Comment by bbuccianti** [comment]
> Actually document the REPL's readline support and tab completion via the optional readline.lua dep so people know it's there and what it can do!

Someone has taken this?

I can make an attempt if nobody is doing it.

**Comment by technomancy** [comment]
@jaawerth did you have this already in progress, or is it in a good place to hand off?

**Comment by jaawerth** [comment]
Yep, I've got something mostly written and should have something PR'd to the `setup-guide` branch this evening. That said, @bbuccianti, if you see anything you want to add or change to it, definitely feel free. I'll tag you when I submit the PR so you can take a gander!

**Comment by technomancy** [comment]
I think this is landed on master but of course there's always room for further improvement!
