### ISSUE TITLE
Support for bitwise operators

### ISSUE THREAD

**Issue by stefandevai** [bakpakin/Fennel#238]
Hello! :)

First of all, congratulations for the language, it's been a pleasure to program using it, I love its simplicity and cleverness.

I was reading the reference but couldn't find something related to [lua bitwise operators](https://www.lua.org/manual/5.3/manual.html#3.4.2) in Fennel. Is there a way to use them?

**Comment by technomancy** [comment]
This is definitely an oversight; I wasn't aware of these operators and had always used bitop functions for portability.

I think it would be a good addition tho! Happy to take a patch, or if not I may get around to it after the jam is over.

**Comment by shtwzrd** [comment]
I would also really like to see the bitwise operators included in Fennel, but am concerned about the operators being available only in Lua 5.3.

Fennel supports and runs CI tests for Lua 5.{1..3} and luajit. 5.1 and 5.2 would require fills or third party libraries to work, and (iirc) luajit has bitwise operators but they work differently from PUC Lua's.

What should Fennel do about bitwise ops for those platforms, if anything?

**Comment by bakpakin** [comment]
Not an issue - we support integer division, a Lua 5.3 only feature and there is no issue with compatibility. Compiled Fennel that uses integer division will not work on top of other Lua versions, but the compiler can emit the code from any “host” Lua version.

**Comment by jaawerth** [comment]
For opt-in portability, we could consider adding a `bitwise.fnl` plugin that patches the specials with macros that expand to the `bit.*` library functions in 5.2 and 5.1:

```clojure
(macros {:band (λ [v ...] "bitwise AND" `(bit.band ,v ,...))
         :bxor (λ [v ...] "bitwise XOR" `(bit.bxor ,v ,...))})

; patch rootScope only in lua 5.3
(eval-compiler
  (when (= _VERSION "Lua 5.3")
    (patch-root-scope-with-macros)))
```
