### ISSUE TITLE
nval optimizations missing from outer scope

### ISSUE THREAD

**Issue by XeroOl** [bakpakin/Fennel#239]
When looking at the generated lua code, I noticed that there is a missing optimization.
This fennel program, when compiled, creates an extra wrapping function.
```fnl
(if true
    (print "true")
    (print "false"))
(print "done")
```
```lua
local function _0_(...)
  if true then
    return print("true")
  else
    return print("false")
  end
end
_0_(...)
return print("done")
```
However, if the entire program is placed within a `(do )`, the outputted code is optimized, without the extra function definition and call.
```fnl
(do (if true
        (print "true")
        (print "false"))
    (print "done"))
```
```lua
if true then
  print("true")
else
  print("false")
end
return print("done")
```
I believe the optimized lua should be emitted for both of these input programs.

**Comment by bakpakin** [comment]
Fixed by #240, closing.
