### ISSUE TITLE
(values)

### ISSUE THREAD

**Issue by XeroOl** [bakpakin/Fennel#241]
Currently, `(values)` doesn't emit correct code in some cases. I've found that `local`, `let`, and `var` can  combine with `(values)` to produce invalid code, but it's possible that there are other forms that cause similar issues. 
```fnl
(local t (values))
```
```lua
local t =
```
`lua:1:unexpected symbol near <eof>`

## Solutions

I've come up with a list of potential ways to solve this problem.

* Change `(values)` to be a compile error (such as "missing argument").
  * No easy way to avoid returning a value.
  * Breaking change that should appear in the changelog.
* Create a special case for no args, ie `(function()end)()`.
  * Potentially has performance implications
* Fiddle with the `nval` optimization so that the current code generation will be correct.
  * I suspect the issue is with the destructuring code.
* Leave the code as is and call `(values)` undefined behavior.
* Potentially something else?

**Comment by technomancy** [comment]
I'm inclined towards the first one because it's easiest and will catch what is likely to be an error, but if you want to take a look at how difficult it would be to make the third one happen, we could talk about going that route instead.
