### ISSUE TITLE
Scope issue in fennel-lang.org repl?

### ISSUE THREAD

**Issue by ergodicbreak** [bakpakin/Fennel#243]
Hi, I ran into confusing output in the fennel-lang.org repl:

> Welcome to Fennel 0.3.2, running on Fengari (Lua 5.3)
> 
> You can run any Fennel code here; try this: (print "Hello world!")

> (local tbl [[] [] []])

> (var foo (. tbl 1))

> (set foo nil)
Compile error in 'set' unknown:1: expected local var foo

From help in IRC this sounds like something peculiar to the fennel-lang.org repl.

**Comment by jaawerth** [comment]
I can confirm the behavior on the website.

> From help in IRC this sounds like something peculiar to the fennel-lang.org repl.

I suspect this is the case, in which case we might want to re-create this issue on the [fennel-lang.org repo](https://github.com/technomancy/fennel-lang.org)
