### ISSUE TITLE
Add table of contents to reference.md

### ISSUE THREAD

**Issue by Benaiah** [bakpakin/Fennel#247]
m455 on IRC suggested that the reference page would be easier to use if it began with a list of internal links to each item that's documented there.

**Comment by m455** [comment]
If I were to do a mock up of the reference page in my spare time, would Markdown be okay as a format?

**Comment by Benaiah** [comment]
This has been solved via a patch to fennel-lang.org - https://lists.sr.ht/~technomancy/fennel/%3C87o8r8sgcg.fsf%40mischenko.com%3E
