### ISSUE TITLE
Setup guide

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#250]
One missing piece in the documentation is it is now is a guide for setup and install of Fennel both for general-purpose use and for various contexts like embedding, love2d, etc. We should also cover readline installation and editor support.

We should take a look at various other languages' getting started guides too.

**Comment by m455** [comment]
I can definitely help with this as well as structuring. If you let me know from an abstract level what readline can do, i can create a skeleton of a document (and even populate a bunch), and then get information from you regarding details, which I can then translate into procedures.

As for editor support. If you list off the editors, I can do the same :)

**Comment by jaawerth** [comment]
The stuff I had in the back of my head as far as general outline would be:

## Installation
### Manual/from git
- `LUA_PATH` and `LUA_PATH_5_3` to ensure proper resolution
- manpages

### luarocks
- Ensuring things installed via luarocks are loadable with `require` by setting the appropriate env vars, particularly with `eval $(luarocks --lua-version=foo path)` (possibly a snippet that can be added to `.bashrc`)

### distro packages
- official OS packages
- brew/nix/guix/aur/other "recipe" package managers

## readline
- installing `readline.lua` to get readline + completion
- optionally using `~/.inputrc` to customize readline behaviors e.g. `blink-matching-paren` (which works in master and will work in 0.4.0)
- using `.fennelrc` to persist a rolling repl history
  ```clojure
  (match package.loaded.readline
    rl   (rl.set_options {:histfile "~/.fennel_history"}))
- maybe mention somewhere that you can also use `rlwrap` to at least get friendlier interactivity, albeit without completion and such.
  ```

**Comment by m455** [comment]
I've started something here that I will continue to update:

https://github.com/m455/setting-up-fennel

**Comment by m455** [comment]
I just submitted a pull request to the setup-guide branch with some more stuff added. Still need to finish some of the editor support sections at the bottom of the document
