### ISSUE TITLE
destructuring k/v tables in Lua 5.3 gives non-deterministic order in compiler output

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#257]
In Lua 5.2 and 5.3, table iteration order with `pairs` appears to be indeterminate. Because [destructuring k/v tables currently uses `pairs`](https://github.com/bakpakin/Fennel/blob/1ffff3f386e1c33362b9aeb33124f66a73b93d89/fennel.lua#L1288), the definition order in the compiled Lua output can change between runs.

The order is consistent in both PUC and LuaJIT versions of 5.1

## Test case

Running this in the shell, with `lua --v gives Lua 5.3.x or 5.2.x`:
```bash
(testcode='(let [{: a : b : c} {:a 1 :b 2 :c 3}] nil)';
for i in `seq 1 10`; do
  echo "$i\t" $(fennel --compile <(echo $testcode));
done)
```
```lua
1	local _0_ = {a = 1, b = 2, c = 3} local b = _0_["b"] local a = _0_["a"] local c = _0_["c"] return nil
2	local _0_ = {a = 1, b = 2, c = 3} local b = _0_["b"] local c = _0_["c"] local a = _0_["a"] return nil
3	local _0_ = {a = 1, b = 2, c = 3} local c = _0_["c"] local b = _0_["b"] local a = _0_["a"] return nil
4	local _0_ = {a = 1, b = 2, c = 3} local c = _0_["c"] local b = _0_["b"] local a = _0_["a"] return nil
5	local _0_ = {a = 1, b = 2, c = 3} local b = _0_["b"] local c = _0_["c"] local a = _0_["a"] return nil
6	local _0_ = {a = 1, b = 2, c = 3} local c = _0_["c"] local b = _0_["b"] local a = _0_["a"] return nil
7	local _0_ = {a = 1, b = 2, c = 3} local b = _0_["b"] local a = _0_["a"] local c = _0_["c"] return nil
8	local _0_ = {a = 1, b = 2, c = 3} local a = _0_["a"] local b = _0_["b"] local c = _0_["c"] return nil
9	local _0_ = {a = 1, b = 2, c = 3} local b = _0_["b"] local a = _0_["a"] local c = _0_["c"] return nil
10	local _0_ = {a = 1, b = 2, c = 3} local a = _0_["a"] local c = _0_["c"] local b = _0_["b"] return nil
```

## Possible fixes

1. The direct fix would be to have `destructure`/`destructure1` in the compiler first build and sort a table of keys , so the output is always consistent.
2. If we created an internal AST node type for k/v tables that keeps track of key order, we could prevent similar issues from cropping up if `pairs` is being used in the compiler, but it would be more work to change.

One possible approach to **2** is to create a `KV_TABLE_MT` that tracks key order, and sets `_pairs` on the metatable to use it. This might save us having to replace `pairs` usage throughout the computer: Lua 5.3 would use `_pairs` to control iteration, while older versions would compile differently from 5.3 but be internally consistent.

**Comment by technomancy** [comment]
As long as this is only a problem in the destructuring implementation and not elsewhere in the compiler I'm inclined to stick with option 1. It would have the benefit of more consistency across Lua versions, which is not required but is nice to have.

Option 2 is complicated by the fact that we use the metatable of non-list table literals to store source data (filename/line/byte-offset) and so changing it so every table had the same metatable would result in some difficulty there: https://github.com/bakpakin/Fennel/commit/91d88ac5ee1732f8c79e759adada00fa7d82a08a
