### ISSUE TITLE
let block inside loop discards last body form

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#26]
I found a bug where the last form of a `let` block inside a loop (both `each` and `for`) is discarded:

```lisp
(for [_ 1 3] (let [] (form1) (this-form-gets-discarded)))
```

I think it has to do with an in correct `nval` setting when `let` calls `doImpl` but I'm having trouble tracing it beyond that.

There's a failing test case on this branch: https://github.com/bakpakin/Fennel/tree/let-inside-loop

**Comment by bakpakin** [comment]
I have found and fixed the bug. Your test case, however, is incorrect. 'for' always returns nothing.

The problem happened when let was not in tail position or the direct child of a 'set' (no target set), which is why it happened in the for loop, as nothing in the loop is in tail position.

**Comment by technomancy** [comment]
Oh, hah; of course for is always nil.

Thanks for the quick fix; I'll take a look at the patch and hopefully learn a thing or two about how tail calls are tracked.
