### ISSUE TITLE
rename new bitwise operators?

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#261]
@bakpakin added Lua 5.3 bitwise operators in #251 (for issue #238), currently named `<<`, `>>`, `&`, `|`, `xor`, and `bnot`. For consistency, I'd like to suggest we update the names:

## New names
- `<<` to `lshift`
- `>>` to `rshift`
- `&` to `band`
- `|` to `bor`
- `xor` to `bxor`
- `bnot` stays the same

This is consistent, leaves symbols like `&` open for us to use in future, and matches the names used by LuaJit's `bit.*` extension library. If we add an optional module that sets fallback macros for earlier Lua versions, those same macros can be overridden to e.g. dispatch to the `bit.*` library when it's available.

## Downside

One possible downside to mirroring the `bit.*` names is that it would conflict if people want to follow the not-uncommon pattern of `(local {: lshift : rshift : bxor} bit)` in LuaJIT.

However, if not the above, adding a common prefix (even if it's just `b` or `bo` for "binary operator") would help keep cognitive debt to a minimum by providing a visual cue that these specials only work in Lua 5.3. Open to suggestions!

## Docstrings
It would also be a good idea to ensure the docstrings for all of them make it clear they only work in Lua 5.3.

**Comment by technomancy** [comment]
@bakpakin any objections on this since you implemented this originally?

**Comment by bakpakin** [comment]
No problem with this - I’m not sure the operations are common enough in Lua (so by extension, Fennel) to absolutely require the shorter names - and as pointed out, keyboard keys are in short supply :)
