### ISSUE TITLE
Source is in one File

### ISSUE THREAD

**Issue by bakpakin** [bakpakin/Fennel#27]
The majority of the source code is all in one file. For someone familiar with the codebase, this isn't a huge problem, but I think it makes the code base seem more complex than it really is. Most of the code could easily be refactored into separate files/modules, such as ones for streams, parsing, common data structures, core compilation and compiler helpers, and various individual files for special forms.

As I am familiar with the code, I am wondering if people think this would be helpful for making the code more readable.

**Comment by technomancy** [comment]
I get where you're coming from, but personally I found it quite easy to navigate as a single file.

It reads very linearly from parser -> compiler -> special forms -> API entry points, so it tends to be very easy to find what you need. Maybe just some comment headers to make those sections more distinct?

I think there's something quite appealing about being able to drop a single file into your codebase and get everything you need.

**Comment by bakpakin** [comment]
Interesting, just wanted a second opinion. I will close this for now.
