### ISSUE TITLE
[0.4.0] self-contained cli not quite self-contained

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#278]
Noticed that having another fennel version on my `package.path` was causing that to be loaded by the supposed-to-be-self-contained launcher script, overriding the version that should be preloaded.

I suspect this is caused by an ordering issue with `--require-as-include`; we may just need to tweak the order preloads are generated at the top of the file when there are multiple `include`s.

**Comment by jaawerth** [comment]
I've narrowed this down to the root cause; because the `include` special does the preloading as follows when the include target is a Fennel module:

```lua
local forms = list(sym('or'), targetForm, list(sym('fn'), sequence()))
local p = parser(stringStream(s), path)
for _, val in p do table.insert(forms[3], val) end
compile1(forms, subscope, subChunk, subopts)
```

The above use of `list(sym('fn'), ..)` results in pointlessly setting metadata (in this case an empty arglist) on the generated loader function. This generates a `require("fennel")` that bypasses `--require-as-include` due to it being directly emitted by the `fn` special.

The three approaches that come to mind for fixing this are:

1. Modify `include` to not compile the loader set on `package.preload`, but to instead emit it directly as a function, and compile the source module to a string and simply append it to the body.
2. Modify the `fn` special to override the overall `useMetadata` setting.
3. Modify `fn` to skip setting metadata if there's no docstring and the arglist is empty.

**Comment by technomancy** [comment]
I've been thinking of a different approach for `--require-as-include` anyway. The current one is limited only to direct `require` calls, which makes self-contained builds of limited use since they quit working as soon as one lua module loads another one.

What if `--require-as-include` functioned by introducing a `package.searcher` entry? It could load the module in question, which would cause the searcher to be re-invoked for each new transitive `require`.

The downside of course would be that people might not expect compilation to cause code to run, but I don't really see any other way of getting `--require-as-include` to work reliably.

**Comment by jaawerth** [comment]
I'd be wary of doing this for 0.4.1. While writing a module with top-level side-effecting code isn't a great idea and should be pretty rare, I suspect this would make the use of `--require-as-include` more brittle than it already is, considering scenarios like:

- a module contains env-dependent conditional require calls based on platform, env vars, optional deps, etc; this could lead to different bundles based on conditionals at compile time for checks that were meant to happen during runtime
- a module is performing system side effects like writing to a file, etc (should be pretty rare, but it's not impossible someone may want to require a file that just performs an action and wasn't written as a module)
- we'd still get unreliable bundling results for any requires that target a C-bound module

I don't think these concerns are necessarily insurmountable, but I'd be pretty hesitant to make a change like this for a minor release unless it was bulletproof. Might be worth considering for a long-term solution, though?

Once we have a plugin system, we can of course whip up a plugin that uses an actual lua parser to better bundle nested Lua requires. In the meantime, we could make `--require-as-include` a bit easier to work with by making it configurable somehow. Perhaps a way to set a dependency map for lua modules, so people can feed requires in?

For now, though, I think a less invasive change that fixes this particular bug would be ideal, even if we end up overhauling `--require-as-include` for 0.5.0.

Thoughts?

**Comment by technomancy** [comment]
Yeah, overhauling `include` is a bigger project that shouldn't be in this next release.

I think of the options for fixing this particular bug, modifying `include` to emit lua directly instead of compiling a function is going to make the most sense.
