### ISSUE TITLE
Float parsing curiously working

### ISSUE THREAD

**Issue by octplane** [bakpakin/Fennel#28]
Hello,

It seems the float parsing is broken in some way:

```lisp
(do
    (set a 0.3)
    a
)
```

```lua
fennel --compile test.fnl                                                                                                                                   do
  a = 0.29999999999999999
  return a
end
```

Is this intended?

**Comment by bakpakin** [comment]
The parser uses the function tonumber to parse numbers. It then uses string:format to print the numbers to 17 digits of precision

```lua
        local n = ('%.17g'):format(ast)
```
These numbers should either round to the same floating point number when parsed.

**Comment by octplane** [comment]
Indeed, thanks for the info.
