### ISSUE TITLE
[0.4.0] AST not applying SEQUENCE_MT to seq literals

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#286]
It looks like sequential table literals are no longer being given `SEQUENCE_MT` in the ast, which is breaking the `sequence?` function in the compiler env, giving it false positives. This could cause issues when validating input to macros that accept e.g. a binding vector.

### Expected behavior (correct in 0.3.2)
```clojure
(macro seq-literal? [expr] (sequence? expr))
(seq-literal? [:a :b :c])
; => [:a :b :c]
```
### Actual (in 0.4.0 and current master)
```clojure
(macro seq-literal? [expr] (sequence? expr))
(seq-literal? [:a :b :c])
; => false
```

**Comment by jaawerth** [comment]
I also noticed that the compiler env has both `list?` and `list` functions exposed, but for sequences, only `sequence?` is exposed. We may want to expose the `sequence` function to the compiler env for symmetry; it can also be useful for quickly generating one from input, e.g. `(sequence one two (unpack some-table))`.

**Comment by jaawerth** [comment]
Even weirder, in both 0.3.2 and 0.4.2, it turns out:
- `isTable` is correctly ruling out tables with `LIST_MT` as the metatable, but not `SEQUENCE_MT`, which may or may not relate to the cause of this issue if there's a false positive on an internal check
- This actually runs without complaint because `let` is using `isTable` instead of `isSequence`:
  ```clojure
  (let {1 x 2 9 3 y 4 2} (* x y)) ; => 18
  ```

This part could require some deep changes if `isTable` is being used in too many places where it could be sequential or not, so fixing this aspect may need to wait until after 0.4.1 if we want to fix our current bugs without possibly introducing new ones, but we should at least make sure `SEQUENCE_MT` is being applied to sequential table literals, and it's worth at least looking into whether we can update `isTable` without breaking things..

**Comment by technomancy** [comment]
> isTable is correctly ruling out tables with LIST_MT as the metatable, but not SEQUENCE_MT, which may or may not relate to the cause of this issue if there's a false positive on an internal check

I don't think this is a mistake; `isTable` should accept both k/v tables and sequence tables.

On account of how easy it is to lose the metadata, I'm not sure it's a good idea to make `let` be more picky about whether the `SEQUENCE_MT` is set or not. But we should definitely fix `sequence?` to be accurate.

**Comment by jaawerth** [comment]
> I don't think this is a mistake; `isTable` should accept both k/v tables and sequence tables.

That's a fair point, and you can always do `(and (table? v) (not (sequence? v)))` if you need to differentiate.
 
> On account of how easy it is to lose the metadata, I'm not sure it's a good idea to make `let` be more picky about whether the `SEQUENCE_MT` is set or not. But we should definitely fix `sequence?` to be accurate.

Works for me. Per my comment on the PR, I'm not sure storing the byte/line metadata on the metatable is the best approach, compared to just using a weaktable to store per-instance metadata, since to hack around it we're not generating fresh metatables for every sequence node in the AST. But since going the weaktable route would result in having to rewrite changes that have already been merged to master, we can move forward with this for 0.4.1 and always revisit later when we have more time to test other implementations.
