### ISSUE TITLE
Add online demo

### ISSUE THREAD

**Issue by daurnimator** [bakpakin/Fennel#3]
Easy to do with fengari.

For fun, try on https://fengari.io/:
![image](https://user-images.githubusercontent.com/127971/36291374-9d58f1fc-131e-11e8-8b30-357f7218a100.png)

For those that want to copy/paste:
```lua
package.preload.fnl = loadfile("https://raw.githubusercontent.com/bakpakin/fnl/master/fnl.lua")
require "fnl".eval([[  (print 'hello, world!')  ]])
```

**Comment by bakpakin** [comment]
@daurnimator  This is really awesome btw. I tried taking a poke at it, but I noticed I couldn't do io.read from standard input (there was no io table). Is there another way we turn this into a fnl repl?

**Comment by technomancy** [comment]
I have a WIP stash thing that lets you provide your own IO functions: `fnl.repl({read=myread, write=mywrite})` which might be useful for this. I can put together a PR.

**Comment by bakpakin** [comment]
That sounds great, as long as we can get input from within fengari.

**Comment by daurnimator** [comment]
> I tried taking a poke at it, but I noticed I couldn't do io.read from standard input (there was no io table)

Well yeah. In a browser `io.read` (which blockingly reads from stdin)  doesn't really make sense: what what it read from? The only blocking primitive for input in a browser is `prompt()` which isn't going to be nice to use.

> Is there another way we turn this into a fnl repl?

The repl is written in lua itself: it should be easy to write a fnl repl in fnl (or lua) if you so choose :)
See https://github.com/fengari-lua/fengari.io/blob/master/static/lua/web-cli.lua

**Comment by technomancy** [comment]
> In a browser io.read (which blockingly reads from stdin) doesn't really make sense: what what it read from?

This is pretty easy to address if you have coroutines. I wonder if they just
haven't gotten around to it yet or if there are technical reasons
preventing their implementation of coroutines from working here.

**Comment by daurnimator** [comment]
Sure it's easy to read input with coroutines, but `io.read` isn't. Documented to use coroutines: so it's necessary for a user to implement it themselves.

**Comment by technomancy** [comment]
@bakpakin I've got a prototype of this working decently, but I thought it would be nice to have a proper site up at https://fennel-lang.org or something like that to host it on. Thoughts?

**Comment by bakpakin** [comment]
Yeah, I suppose I could buy a domain.

Is your prototype completely static? Maybe we could host with github pages and just redirect the domain to github. In the long term, it might be better to make a the site in a separate repo.

**Comment by technomancy** [comment]
> Yeah, I suppose I could buy a domain.

I could handle the registration and hosting if you don't want to be bothered, but I'd understand if you want to keep it in your name.

> Is your prototype completely static? Maybe we could host with github pages and just redirect the domain to github. In the long term, it might be better to make a the site in a separate repo.

From the server side it's all static, yeah. So GitHub pages would work fine. The Fengari <script> and the repl <script> are the only non-static parts in the browser.

**Comment by bakpakin** [comment]
> I could handle the registration and hosting if you don't want to be bothered, but I'd understand if you want to keep it in your name.

Great thanks. You can put it in your name, I don't mind.

**Comment by technomancy** [comment]
Let me know if there's anything you think should be changed on https://fennel-lang.org; the repo for the site is at https://github.com/technomancy/fennel-lang.org but we can move it to under your account if you'd prefer.

I was pretty impressed with how easy it was to integrate Fengari once I got over a few hiccups mostly due to me having forgotten most of what I know about publishing on the web. I had to add a hacked version of `io.open` to get the macro tests working, but other than that it passes the test suite just fine.

**Comment by bakpakin** [comment]
Looks great for now, if a bit bare bones. Repl is awesome!

I noticed that the _ and __ bindings for the repl weren't working, but then I noticed that they regressed in the master branch as well, so I just pushed a fix. They should bind to the last values and last values respectively.

**Comment by technomancy** [comment]
Oh yeah, I forgot to mention it's using the actual repl loop stolen straight from fengari.io. Will have to adapt it to use the proper `fennel.repl` to get features like `_`.
