### ISSUE TITLE
even # assertion on quoted table-literals in compiler env

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#303]
Currently, the assertion on even numbers of values in `{}` literals is made in `fennel.parser`, so it throws before any interpolation can happen in `doQuote`. This makes sense on the surface, but adds limitations on generating literals in macros that I think, ideally, it'd be nice to avoid.

## Repro
```clojure
(macro table-of [...] `{,...})
; Parse error in repro.fnl:1 expected even number of values in table literal
```

### Real-world usecases
The above is fairly arbitrary; where this *can* come up is when writing macros that involve emitting a table literal as part of a larger quoted expression. Instead of doing, say,
```clojure
{:x 1 :y 2 ,(unpack extra-values)}
```
You're forced to write something like
```clojure
(let [tbl `{:x 1 :y 2}] (for [i 1 (# extra-values) 2]
  (table.insert tbl (. extra-values i))
  (table.insert tbl (. extra-values (+ i 1))))`
```
This isn't the end of the world, but it can get a smidge unwieldy.

## Solution

All this should really take is to either move that assertion out of the parser, so it's done somewhere when actual code is emitted, or to simply add some kind of exception for `doQuote` so it lies to the parser and instead does the assertion after the interpolating if there are quoted `{}` containing a dynamic unquote.

## To fix, or not to fix?

There may be some complications I'm not thinking of that would make this a `wontfiix`. We may want to at least put off tackling it until after we've got everything self-hosted.

**Comment by technomancy** [comment]
Do you mean moving it out of the parser, not the compiler?

I agree the current check is done too early. Ideally it would happen
after macroexpansion, but I'm not sure quite how that would look. It
might need to be special-cased as part of the quoting implementation as
you say.

My preference would be to address this after we work towards self-hosting.

**Comment by jaawerth** [comment]
Yeah sorry, I edited it but you wouldn't have seen that via email ;-)

I did want to check that there's agreement that we should fix it; since there is, I agree on both counts. Unless it's a trivial change, we should wait until after self-hosting to avoid doing it twice. And if the cleanest solution turns out to be special-casing quoted forms, it won't be a trivial change.

For now we'll call it **blocked on self-hosting**

**Comment by technomancy** [comment]
Catching up with discussion we had on IRC, a better workaround here is to just add one extra arg before the `...` argument in your macro:

    (macro table-of [first-key ...] `{,first-key ,...})

Doing this downstream of the parser means that the parser would have to somehow emit tables that have keys with no values or values with no keys. Since the parser must emit tables of some kind which get used by macros and such, we could determine a system for representing incomplete tables, but it would be awkward to consume these from within macros, and it's easier to explain the workaround above than it is to explain an encoding system that lets us represent invalid tables.

**Comment by technomancy** [comment]
I think we decided the workaround above would be better than implementing this in the parser.
