### ISSUE TITLE
Unable to influence the path of fennel module in Lua embeded app

### ISSUE THREAD

**Issue by rkc-rkc** [bakpakin/Fennel#304]
When using Fennel in [Darktable](https://www.darktable.org) (it embeds Lua 5.3) to write scripts there seems to be no way to influence the fennel path where it looks for module. The canonical location for scripts in Darktable is the 'lua' sub-folder under the config directory, which is not in the default fennel path. The only option seems to be to set the 'FENNEL_PATH' in the environment before launching Darktable.

Setting the Fennel.path in Lua bridge code does not work as the fennel code uses 'private' variable.
Not sure how to set the environment variable from within the Lua bridge code.

I got it working by hard coding the path and invoking fennel.dofile initially and using the env variable subsequently but would rather just use require(). Don't want to go the route of FENNEL_PATH as I would like to share the scripts and reduce friction.

Is there an alternate way to do this?

(new to Lua and Fennel but not to coding)

**Comment by technomancy** [comment]
Hey, thanks for raising this issue.

If you're on the latest stable release, then you should be able to adjust the path like so:

```lua
local fennel require("fennel")
fennel.path = "whatever/?.fnl"
```

However, it looks like the latest master isn't working for this due to a refactoring that was supposed to just rearrange a few things but ended up preventing the change to the `fennel.path` field from propagating back to the code that did the module searching.

I'll push a fix for this which should bring back the ability we had in the last stable release. Thanks for reporting it. Good luck scripting Darktable!

**Comment by rkc-rkc** [comment]
Thanks in advance for the fix

A) While you are at it, I noticed a small redundancy in the searchModule function
```
    local function searchModule(modulename, pathstring)
        local pathsepesc = escapepat(pkgConfig.pathsep)
        local pathsplit = string.format("([^%s]*)%s", pathsepesc,                                                                                                  
                                        escapepat(pkgConfig.pathsep))
```
The escapepat function used  in the string.format can be replaced by pathsepesc

B) Can the debug flag be enabled from the Lua bridge code similar to the change to the path?

Thanks

**Comment by technomancy** [comment]
> A) While you are at it, I noticed a small redundancy in the searchModule function

Good catch; thanks!

> B) Can the debug flag be enabled from the Lua bridge code similar to the change to the path?

Not currently, but that's a good idea that we should add. Do you want to take a shot at this?

**Comment by jaawerth** [comment]
> A) While you are at it, I noticed a small redundancy in the searchModule function

Whoops, that was a silly one. Fixed, thanks for pointing it out!
