### ISSUE TITLE
Failed to install fennel via luarocks

### ISSUE THREAD

**Issue by edubart** [bakpakin/Fennel#307]
When running:
```
luarocks install --local fennel
```

I get this error:
```
Installing https://luarocks.org/fennel-0.4.2-1.src.rock

fennel 0.4.2-1 depends on lua >= 5.1 (5.3-1 provided by VM)

Error: Failed copying fennel
```

My setup is updated ArchLinux, luarocks 3.3.1 and lua 5.3.5. Usually am able to install and run other luarocks packages fine. I tried installing an old rockspecs and `fennel-0.4.1-2.rockspec` install fine, while more recent one fails.

**Comment by technomancy** [comment]
Interesting; I wonder if this is a bug in luarocks. The same dependency is declared in 0.4.1 which works fine.

I have no idea how to fix this unfortunately; I suggest an alternate installation method for now.

**Comment by jaawerth** [comment]
It looks like the issue is that the archive at https://fennel-lang.org/downloads/Fennel-0.4.2.tgz got uploaded without the built `fennel` cli and other built assets. The rock uses that as the source, so fixing that asset should also fix the rock.

**Comment by technomancy** [comment]
Looks like this was just a misleading error message from Luarocks; the Lua version had nothing to do with the failure, and @jaawerth was right about the root cause. The tarball has been updated and 0.4.2-2 has been released which will fetch the right version. Thanks for catching this!

**Comment by edubart** [comment]
I confirm that it is working now, great!
