### ISSUE TITLE
setup guide: move repl/readline section & fix ToC

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#309]
Just filing this so I/we don't forget to make a couple tweaks to the setup guide.

I noticed that in the [setup guide](setup.md),
- The section about adding/configuring readline support in the REPL is under the "Adding Fennel support to your text editor" section. We should move it to somewhere more appropriate
- The top-level ToC link for the readline section is broken

**Comment by technomancy** [comment]
I've added a pandoc-generated TOC on all guides here: https://git.sr.ht/~technomancy/fennel-lang.org/commit/4ae7c6576518cde97bc172de128a9de3147e7704

but the existing markdown file has TOC entries in it that are now redundant.

**Comment by technomancy** [comment]
The latest changes to the setup guide move it so readline setup comes right after "Adding Fennel support to your text editor" instead of under it. I think that covers this issue, right?
