### ISSUE TITLE
add table of contents to tutorial.md

### ISSUE THREAD

**Issue by uvtc** [bakpakin/Fennel#316]
The tutorial is long enough that I think a table of contents at the top would make it easier to find your way around.

I see the reference.md has one, and looks good.

**Comment by technomancy** [comment]
Agreed. Let's do this consistently for all guides published on fennel-lang.org the same way we do for the reference.

**Comment by technomancy** [comment]
This should should be taken care of in https://git.sr.ht/~technomancy/fennel-lang.org/commit/4ae7c6576518cde97bc172de128a9de3147e7704
