### ISSUE TITLE
add table of contents to setup.md

### ISSUE THREAD

**Issue by uvtc** [bakpakin/Fennel#317]
I found it difficult to find my way through this file. It currently has a sort of ad-hoc ToC embedded here and there throughout the document. I think it would be greatly cleaned up if those links throughout were removed, and a big ToC were at the top instead.

I was especially confused at the end, regarding adding readline support, which seemed to continue on as additional sections, where only the first one was linked to in the ad-hoc mini ToC.

Do you think this would be an improvement?

**Comment by technomancy** [comment]
We actually already have this tracked for the setup guide in #309 but I think it's a good idea. For the reference, we use pandoc to auto-generate the TOC, and I think we should apply the same functionality more consistently across all our docs: https://git.sr.ht/~technomancy/fennel-lang.org/tree/master/makefile#L23
