### ISSUE TITLE
Empty lambdas don’t return nil

### ISSUE THREAD

**Issue by bastienleonard** [bakpakin/Fennel#320]
The following code:

```clojure
(lambda test [a])
```

Compiles to:

```lua
local function test(a)
  return assert((nil ~= a), ("Missing argument %s on %s:%s"):format("a", "src/main.fnl", 28))
```

So the function returns `assert()`’s return value, which is true. Shouldn’t it be nil?

**Comment by technomancy** [comment]
You're right; that's a good point. It should return nil.
