### ISSUE TITLE
gensym in method calls triggers side-effects early

### ISSUE THREAD

**Issue by bastienleonard** [bakpakin/Fennel#323]
Minimal example:

```clojure
(lambda and-test []
  (and false
       (: (foobar) :method?)))
```

Latest master generates this:

```lua
local function and_test()
  local _0_ = foobar()
  return (false and _0_["method?"](_0_))
end
```

Now `foobar()` gets called even when the first operand to `and()` is false.

A less contrived example could be:

```clojure
(lambda normal-test []
  (and (not= something nil)
       (: (foobar something) :method?)))
```

Strangely enough, the issue only seems to happen when the symbol ends with a question mark.
`foobar` also has to be a function that we call, not a direct call through a variable.

**Comment by technomancy** [comment]
Yikes, nice catch! Looks like this bug has been around a while.

**Comment by technomancy** [comment]
Turns out this affected more than just method calls; comparators were also hit by the same bug.

The fix adds a bit of overhead but it should only be applied when necessary, and it should be safe against this bug now.
