### ISSUE TITLE
Setup and Tutorial still mention `fennel.lua`

### ISSUE THREAD

**Issue by p-himik** [bakpakin/Fennel#330]
The commit baca2551f70c4ba04be81d7fa135c5798c39af43 has moved `fennel.lua` to `old/fennel.lua` and, as far as I understand, has switched Fennel itself from Lua to Fennel.

With that being said, it's now unclear how to embed it. [Setup](https://github.com/bakpakin/Fennel/blob/main/setup.md) and [Tutorial](https://github.com/bakpakin/Fennel/blob/main/tutorial.md) still mention `fennel.lua` - but how should I actually get it to make sure that the latest version is used?

**Comment by technomancy** [comment]
Good point! The file `fennel.lua` is now compiled rather than being checked in, so you run `make` to generate it from a source checkout, or get it from the release tarball.

I've included an explanation in 650f0ad; do you think that explains it well?

**Comment by p-himik** [comment]
Absolutely, thanks!
