### ISSUE TITLE
Is there a way to transform a function to lua equivalent ?

### ISSUE THREAD

**Issue by tami5** [bakpakin/Fennel#333]
Hi there, Is there a way to transform (i.e. compile) a function to lua equivalent. I'm essentially trying to insert a the equivalent lua function to a file, so I'd appreciate it if someone can tell me if its possible.

Thanks

**Comment by technomancy** [comment]
You'll have to be more specific in your question; this entire project is all about compiling Fennel functions to Lua. Can you provide more detail?

**Comment by tami5** [comment]
Co fnl to lua

@technomancy Sorry for being ambiguous, allow me to explain better through code example. Essentially I want to get a string of lua code from the following code snippet 
(in which I’ll append later to a file programmatically):

```clojure
(fn introduce_app [name] 
  (print (.. "Welcome to " name)))
(introduce_app “my cool app”)
```

Into ...

``` 
function xxx [x]
  -- (note xxx means I don’t care what the namespace)
   print(“welcome to ” .. name)
end 
xxx(“my cool app”)
``` 

My question here is it possible to have this string from some sort of function?

Another thing challenge I have is with function defined in a table which imported from elsewhere :

```clojure
(def x {{:name “alpha” :func <function>}})
;; so that when I call the follow would work
(x.func) ;; it is anonymous function 
```

Hope this clarified what am looking for

Thanks a lot

**Comment by technomancy** [comment]
I'm still having a hard time getting clarity.

Do you mean that you want to take a function which has already been compiled, and turn it into a string of Lua source code at runtime? I'm afraid this is impossible since by that time the Fennel source is not accessible. However, you can turn it into Lua bytecode using `string.dump`, and you can write that bytecode to a network socket or to disk, or whatever. Or you can try to find the source code that was used to produce the function, and compile that to Lua.

Maybe it would help to understand the context and the reason you need this.

(If you have the Fennel source as a string and you want to turn that into Lua source, then you can use `fennel.compile-string` to do that, but I don't think that's what you're asking.)

**Comment by tami5** [comment]
Thank a lor @technomancy appreciate it .

**Comment by tami5** [comment]
@technomancy I've tried string.dump like 

```
(string.dump #(print "hello" ))
```

I got this 
```
"\27LJ\2\0.@/home/tami/repos/nvim/fnl/core/compile.fnl&\0\0\2\0\2\0\3\4A\0026\0\0\0'\1\1\0D\0\2\0\nhello\nprint\1\1\1\0\0"
```
Now thats supper wired output, does appending it to lua file will run it?

Thanks

For my use case, I have a files that defines a map/dict and within them I define functions accessible by a key. During startup of my neovim this maps are collected in another map which I Iterate over is part of my startup method. The issue is that this map is defined within another function (the register function). My goal is to skip running my startup method every time I startup neovim (which is pointless if source code didn't change) so I'm working on instead compile down to my configuration to lower level. The last thing I need to compile is the exec function. Here is the map where the function I need to compile to lua code.

```clojure
(d.use {:repo "nvim-lua/telescope.nvim"
        :opt true
        :packadd true
        :highlights
        [["NormalFloat"              "base05" "base00"]
         ["TelescopeBorder"          "base01" "base00"]
         ["TelescopeMatching"        "base08" "base00"]
         ["TelescopeSelection"       "base07" "base00"]
         ["TelescopeNormal"          "base05" "base00"]]
        :exec ;;; <-- here
        #(do
          (def- actions (require "telescope.actions"))
          (def- tele (require "telescope"))
          (tele.setup
            {:defaults
             {:prompt_position "top"
              :sorting_strategy "ascending"
              :mappings
              {:i
               {:<C-j> actions.move_selection_next
                :<C-space> actions.move_selection_next
                :<C-k> actions.move_selection_previous
                :<esc> actions.close
                :<C-u> actions.preview_scrolling_up
                :<C-d> actions.preview_scrolling_down
                :<CR> actions.goto_file_selection_edit
                :<C-s> actions.goto_file_selection_split
                :<C-v> actions.goto_file_selection_vsplit
                :<C-t> actions.goto_file_selection_tabedit}
               :n
               {:<C-j> actions.move_selection_next
                :<C-k> actions.move_selection_previous
                :<C-c> actions.move_selection_previous
                :<esc> actions.close
                :<CR>  actions.goto_file_selection_edit
                :<C-s> actions.goto_file_selection_split
                :<C-v> actions.goto_file_selection_vsplit
                :<C-t> actions.goto_file_selection_tabedit
                :<C-u> actions.preview_scrolling_up
                :<C-d> actions.preview_scrolling_down}}}}))})
```


I tried the string dump on it and I got the following output

```
"\27LJ\2\0/@/home/tami/.config/nvim/lua/auto/finder.lua�\6\0\0\b\1$\0CjI\14+\0\0\0006\1\0\0'\2\1\0B\1\2\2-\2\0\0009\2\2\2=\1\3\2\18\0\1\0+\1\0\0006\2\0\0'\3\4\0B\2\2\2-\3\0\0009\3\2\3=\2\5\3\18\1\2\0009\2\6\0015\3\"\0005\4
\0005\5\27\0005\6\b\0009\a\a\0=\a\t\0069\a\n\0=\a\v\0069\a\f\0=\a\r\0069\a\14\0=\a\15\0069\a\n\0=\a\16\0069\a\17\0=\a\18\0069\a\19\0=\a\20\0069\a\21\0=\a\22\0069\a\23\0=\a\24\0069\a\25\0=\a\26\6=\6\28\0055\6\29\0009\a\f\0=\a\30\0069\a\a\0=\a\t\0069\a\n\0=\a\v\0069\a\f\0=\a\r\0069\a\14\0=\a\15\0069\a\17\0=\a\18\0069\a\19\0=\a\20\0069\a\21\0=\a\22\0069\a\23\0=\a\24\0069\a\25\0=\a\26\6=\6\31\5=\5!\4=\4#\3D\2\2\0\0�\rdefaults\1\0\0\rmappings\1\0\2\21sorting_strategy\14ascending\20prompt_position\btop\6n\n<C-c>\1\0\0\6i\1\0\0\n<esc>\nclose\t<CR>\29goto_file_selection_edit\n<C-v>\31goto_file_selection_vsplit\n<C-u>\25preview_scrolling_up\n<C-t>
goto_file_selection_tabedit\14<C-space>\n<C-s>\30goto_file_selection_split\n<C-k>\28move_selection_previous\n<C-j>\24move_selection_next\n<C-d>\1\0\0\27preview_scrolling_down\nsetup\ttele\14telescope\factions\19aniseed/locals\22telescope.actions\frequire\1\3\3\3\4\4\4\5\a\t\t\t\n\n\n\v\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r_0_0\0actions0\0\2Bv_0_\0\3\4tele0\0\5:v_0_\0\3\4\0\0"
```

**Comment by technomancy** [comment]
> @technomancy I've tried string.dump like (string.dump #(print "hello"))
>  ...
> Now thats supper weird output, does appending it to lua file will run it?

No, the dumped bytecode string needs to get passed to the load function,
or loadstring on older lua versions. For instance:

    >> (local f #(print :hi))
    >> (local f2 (-> f string.dump load))
    >> (f2)
    hi

> The issue is that this map is defined within another function (the
> register function). My goal is to skip running my startup method every
> time I startup neovim (which is pointless if source code didn't
> change) so I'm working on instead compile down to my configuration to
> lower level.

You said at first that you want to skip running your startup config. But
then you also said you want to run your config, but compiled down to a
lower level? I don't understand what you're trying to accomplish.

I'm guessing you don't actually want to skip running the code, and that
you just want to improve the startup time or something? You should be
able to perform ahead-of-time compilation on any Fennel code to compile
it to Lua if you have found that the Fennel compilation takes too
long. (I have never seen this be the case personally, but of course it
is possible.) Is there something about doing AOT compilation that is
causing a problem?

You should be able to run something like "fennel --compile
myconfig.fnl > myconfig.lua" and then the Fennel compilation process
wouldn't have to re-run every time you start your program.

**Comment by tami5** [comment]
Oh no no nothing wrong with fnl, its just how my code is written and how many files it needs to reads. Its just I'm reading my code that uses vim api and compiled down to simple form to improve startup. What I'm trying to accomplish is simply skip calling a number of function at startup if nothing is changed in my source code, and instead load/source a single file where I collect all the output from function like d.use above.

I've reach the load (string.dump (fun ... , but my issue now is here #334. 

Thanks again, and sorry for giving you such a hard time.

**Comment by technomancy** [comment]
> What I'm trying to accomplish is simply skip calling a number of
> function at startup if nothing is changed in my source code, and
> instead load/source a single file where I collect all the output from
> function like d.use above.

That sounds like a much better fit for AOT compilation; is there some
reason you can't use that instead? Any computation that happens in
macros will be done during compile time only and not repeated on every startup.

As far as I can tell, all the mechanisms to do what you're looking for
already exist in the compiler. Perhaps there is something about them
that I'm missing which make them unsuitable, but I would look there first.

**Comment by tami5** [comment]
please check out my configuration written in fnl and I'd love to get your thoughts. https://github.com/tami5/nvim 

AOT is something new to me.
