### ISSUE TITLE
Is there double bracket like escape sequence in fennel?

### ISSUE THREAD

**Issue by tami5** [bakpakin/Fennel#334]
Hey everyone, I'm trying to write a byte code to a lua file that I can later run. 

Unfortunately, I have to deal with escape sequences. I've test writing string generate from `string.dumb` and wrap it with `"load(\"%s\")()"` but the escape code get transformed and "\n" becomes new line. However, when I tested the lua double bracket everything worked as expected.

Thanks

**Comment by technomancy** [comment]
There is only one kind of string in Fennel but you can still do
escaping; probably what you want is `(string.format "%q" str)`

**Comment by tami5** [comment]
Oh wow thanks @technomancy that gave some progress. Only issue so far is that `\n` get posted to new line
