### ISSUE TITLE
document macros

### ISSUE THREAD

**Issue by robinvd** [bakpakin/Fennel#34]
is there any intention to implement macros in Fennel

**Comment by technomancy** [comment]
There is some undocumented support; you can look at the test suite to see how it works. I would venture to say the current interface is not guaranteed to remain stable, but if you give it a try we'd be interested in hearing what you think about it.

**Comment by robinvd** [comment]
It looks promising, and i'll definitely try it.
```-- can't define and use a macro in the same eval```
this does look like a big limitation

**Comment by technomancy** [comment]
Sorry, that comment is misleading; I meant in a single `eval-compiler` block, not a `fennel.eval` call. But I just checked again and I was mistaken; even in a single `eval-compiler` block you can use a macro as soon as it's defined. It's only special forms which have this limitation.

**Comment by technomancy** [comment]
@robinvd Please take a look at #37; it implements a simpler macro system which has some advantages of not affecting global scope.
