### ISSUE TITLE
Error in `default_on_values' in the fennel binary

### ISSUE THREAD

**Issue by FrankRuben** [bakpakin/Fennel#342]
Hi,

while trying to get some minimal GUI running with Fennel and IUP, I got an error in the Fennel REPL, which caused the REPL to exit.

**Details:**

1. I'm starting a REPL and load my Fennel module using `reload'.
2. I'm getting an error while executing that.
3. The REPL dumps the following error and exits: "fennel:387: bad argument #1 to 'concat' (table expected, got string)".
4. Reason seems to be that function `default_on_values' expects a table, but in that case (error from C) a string is returned (which seems to be OK according to the documentation of `pcall').
5. The issue can be fixed by changing the error message writing as follows: "io.write(type(xs) == "string" and xs or table.concat(xs, "\9"))".
6. I'm not sure whether that's better fixed here in `default_on_values' which is called from different places (and whether `xs' is still a good name for the parameter) or just in the caller for the `reload' command. You'll know that better :).

Thanks a lot for Fennel - great tool - and best regards, Frank

**Comment by technomancy** [comment]
Thanks for catching it! I believe the changes on the latest main branch solves this problem.
