### ISSUE TITLE
Compile for incorrect "." table lookup

### ISSUE THREAD

**Issue by FrankRuben** [bakpakin/Fennel#343]
Hi,

I was writing a bad table lookup, using `(. myfield mytbl)` instead of `(. mytbl myfield)` and got a strange compile error.

To reproduce, compile the following:
```
(fn test [h] (. :name h))
```

This will result in the following Lua code:
```
 local function test(h) return "name"[h] end return test
```

This will yield the following error when being run with Lua:
```
lua: s.lua:1: 'end' expected near '['
```

Stupid me, but still I would hope for a nicer error info :).

Best regards, Frank

**Comment by technomancy** [comment]
Nice catch--I've updated it so we always emit parens around it in order
to keep the Lua valid, for numbers as well as strings just in case.
