### ISSUE TITLE
Odd behaviour with the --correlate flag

### ISSUE THREAD

**Issue by alexjgriffith** [bakpakin/Fennel#344]
I've been noticing that there has been some odd behaviour when compiling using the --correlate flag. 

For large files most of the lua code is compressed in one line at the very bottom of the output file. Even for simple modules, like the one below, the lines of the output do not line up with the input.

### simple.lua
``` clojure
(fn a [b c]
  (+ b c))

{: a}
```

``` bash
fennel --correlate --compile simple.fnl > simple.lua
```

### simple.fnl
``` lua
 local function a(b, c)
 return (b + c) end return {a = a}
```

I'm on the most recent commit 9fe88d9

**Comment by technomancy** [comment]
Thanks for catching this. I think I have a fix with b72aa1d.
