### ISSUE TITLE
Wrap runtime errors to provide source-mapped errors into fennel code

### ISSUE THREAD

**Issue by elkowar** [bakpakin/Fennel#349]
One of the biggest issues with working in fennel currently is that errors (runtime errors) are rather unergonomic.

A nice solution would be to have a "development" compile mode, where each function in the compiled lua is wrapped and annotated with source-maps (like line and file). This would then allow the error message to be enhanced to contain at least a line and file reference to the fennel source, or - optimally - some of the more common errors could be enhanced to actually mention fennel code and concepts directly. This would drastically improve the development experience of working with fennel!

**Comment by elkowar** [comment]
Just found `fennel.traceback` which actually seems to (mostly) be what I'm looking for... I'll close this, sorry!

**Comment by technomancy** [comment]
No problem.

I'm open to suggestions to how to make this easier to find since it
seems in your case it wasn't obvious. Is there somewhere we should add
it to the docs?

**Comment by elkowar** [comment]
I think it's fine, the section in the API primer is pretty obvious. I just didn't think of looking there 👀
