### ISSUE TITLE
Simple way of creating general tables

### ISSUE THREAD

**Issue by leiserfg** [bakpakin/Fennel#353]
Is there a syntax/macro in Fennel to create a general table? I mean one table like   
```lua
{"a sequenced value",  a_key="a value"}
``` 
Some libs use that kind of table as part of their API and having to create two separate tables (sequenced and non-sequenced) and then merge them or creating a sequenced table and then adding each key-value pair seems nonsensical to me.

**Comment by leiserfg** [comment]
One way could be adding a new special `&` value/identifier:
for instance `&i` with a similar behavior as `iota` from `golang`, so one can do
```clj
{:a_key "a value"  &i "a sequenced value"   &i "another sequenced value" }
```
to get the lua output
``` lua
 {a_key="a value",  "a sequenced value",  "another sequenced value"}
```

**Comment by leiserfg** [comment]
It's maybe akward from a  lisp prespective, but it's actually preaty common in lua some libs use that as a replacement for the keyword arguments of python. For insance, in https://github.com/wbthomason/packer.nvim:
```lua
use {
    'haorenW1025/completion-nvim',
    opt = true,
    requires = {{'hrsh7th/vim-vsnip', opt = true}, {'hrsh7th/vim-vsnip-integ', opt = true}}
  }
 ```

**Comment by leiserfg** [comment]
I was checking how does `hy` to solve that while mapping similar apis to python and they also use a `&` special, but instead of one per key, they use one for separating `args` from `kwargs`, IMHO that makes the code harder to read. I understand if you don't  like my proposal, maybe it's not `lispy` enough (I come from python).  But I have seen pepople doing wrappers over that kind of apis (like https://github.com/Olical/dotfiles/blob/master/stowed/.config/nvim/fnl/dotfiles/plugin.fnl#L12-L23)  and I will rader avoid doing that if posible.

**Comment by andreyorst** [comment]
You basically have two options - using `doto` and writing sparse tables:

``` clojure
(use (doto [:haorenW1025/completion-nvim]
       (tset :opt true)
       (tset :requires [(doto [:hrsh7th/vim-vsnip] (tset :opt true))
                        (doto [:hrsh7th/vim-vsnip-integ] (tset :opt true))])))
```

This one actually compiles to the following sparse variant, which is not hard to type in by hand, though, yes, a bit awkward:

``` clojure
(use {1 :haorenW1025/completion-nvim
      :opt true
      :requires [{1 :hrsh7th/vim-vsnip :opt true}
                 {1 :hrsh7th/vim-vsnip-integ :opt true}]})
```

Here are sequential keys are manually addid before the sequential data. 

Another way is to write a macro:

``` clojure
(macro sparse [...]
  (let [args [...]
        t {}]
    (var j 0)
    (each [i x (ipairs args) :until (= x '&)]
      (set j i)
      (table.insert t x))
    (for [i (+ j 2) (length args) 2]
      (tset t (. args i) (. args (+ i 1))))
    t))
```

This macro will add everything sequentially until it sees `&`, then it will add key value pairs:

```
>> (sparse :a :b & :c 10 :d 20)
{1 "a" 2 "b" :c 10 :d 20}
```

But again, it simply generates the associative table with numeric keys for sequential data.

**Comment by leiserfg** [comment]
Thanks @andreyorst, I'm just learning fennel but thanks to your help I came up with a macro that works just as I proposed:
```clj
(macro sparse [...]
  (let [args [...]
        t {}]
    (for [i 1 (length args) 2]
      (let [key (. args i)  val (. args (+ i 1))]
       (if (= key '&i)
        (table.insert t val)
        (tset t key val))))
    t))

(sparse &i :a  :c 10 :d 20 &i 45)
```
Compiles to 
```lua
return {"a", 45, c = 10, d = 20}
```

**Comment by technomancy** [comment]
That's a great solution; thanks.

**Comment by rofrol** [comment]
I have also found this macro:

```fennel
(fn str? [x]
  (= :string (type x)))

(lambda pack [identifier ?options]
  "A workaround around the lack of mixed tables in Fennel.
  Has special `options` keys for enhanced utility."
  (assert-compile (str? identifier) "expected string for identifier" identifier)
  (assert-compile (or (nil? ?options) (table? ?options))
                  "expected table for options" ?options)
  (let [options (or ?options {})
        options (collect [k v (pairs options)]
                  (match k
                    :require* (values :config `#(require ,v))
                    _ (values k v)))]
    (doto options (tset 1 identifier))))
```

And use like this:

```fennel
(import-macros {: pack} :macros)

[(pack :williamboman/mason.nvim
       {:dependencies [:williamboman/mason-lspconfig.nvim]
        :config (fn []
                  (vim.cmd "autocmd FileType mason setlocal winblend=10")
                  (vim.api.nvim_create_autocmd [:BufEnter :BufWinEnter]
                                               {:pattern :*.yml
                                                :callback (fn []
                                                            (vim.diagnostic.hide))})
                  (require :initializers.lspconfig)
                  )})]
```

https://github.com/avegancafe/VimStudio/blob/88f7df47b89804fc6d37612ac9b056b51fb973af/fnl/macros.fnl#L3

**Comment by Olical** [comment]
I hope you don't mind the bump of an old ticket but just wanted to leave this here for people who want a more generic and flexible macro:

```fnl
(fn tx [& args]
  "Mixed sequential and associative tables at compile time. Because the Neovim ecosystem loves them but Fennel has no neat way to express them (which I think is fine, I don't like the idea of them in general)."
  (let [to-merge (when (table? (. args (length args)))
                   (table.remove args))]
    (if to-merge
      (do
        (each [key value (pairs to-merge)]
          (tset args key value))
        args)
      args)))
```

This one accepts a few use case for lazy.nvim and various key mapping Lua syntaxes.

```fnl
(tx "my-plugin")
(tx "-" "<CMD>SomeKeyMap<CR>)
(tx "-" "<CMD>SomeKeyMap<CR> {:desc "foo"})
(tx "plugin" {:opts {}})
```

I just wanted one macro that worked basically like Lua's mixed table type syntax. I still think it's right that Fennel does _not_ include this in the language, I think mixed tables are anti-patterns based on a kind of neat looking Lua syntax quirk.

Thanks to Fennel, we can macro our way around our problems! Thanks for the inspiration to everyone that added their own ideas in this thread.
