### ISSUE TITLE
Introduce "unclean" macros

### ISSUE THREAD

**Issue by YohananDiamond** [bakpakin/Fennel#363]
## Why

As far as I've understood, all symbols bound inside a macro's return body should be quoted, and I think that's a nice thing.
There are, though, some situations where I think it would be really convenient to define symbols that are available outside of the macro call.

## Usage examples

```lisp
;; example one - defining coroutines

;; default way
(local my-coroutine (coroutine.create (fn []
                                        (print 10)
                                        (coroutine.yield)
                                        (print 20))))

;; with an assist `make-coroutine` (clean) macro
(local my-coroutine (make-coroutine []
                      (print 10)
                      (coroutine.yield)
                      (print 20)))

;; with an unclean `def-coroutine` macro
(def-coroutine my-coroutine []
  (print 10)
  (coroutine.yield)
  (print 20))
```

```lisp
;; example two - multiple imports with a custom prefix
;; not sure if it would be really relevant here, though, since we can simply do `my-mod.thing1` to access something.

;; current way of doing things
(local {:thing1 my-mod/thing1
        :thing2 my-mod/thing2}
  (require :my-mod))

;; with a `destructure-with-prefix` macro
(destructure-with-prefix my-mod [thing1 thing2]
                         (require :my-mod))
```

## How to implement?

Unclean macros could be defined the same way as clean macros, but "unclean" symbols would have a different suffix.

```lisp
(local symbol# 10) ; clean symbol declaration ("gensym") - resolves to `local _0_` or something similar
(local symbol## 10) ; unclean symbol declaration - resolves to `local symbol`
(local symbol 10) ; should still error out
```

A `##` might not be the best symbol, though, but I don't have many good ideas for this.

Also, if the defined symbol already exists in scope, I think it shouldn't error out (as the current behavior seems to be in relation to shadowing of local variables):

```lisp
(local x 10)
(local x 20) ; this is currenly valid (as of 0.9.1)
```

### Pros

Some coding patterns might be **made easier without introducing new language constructs**;
(Such as the examples I showed above.)

### Cons

**Might cause confusion**, since it would be harder to know which symbols get defined in a specific scope;
(This can be mitigated by making these macros obey to some kind of naming convention, but it can be hard to implement and it'd make the language more complicated)

**Might discourage solutions better suited to clean macros**, since unclean macros can be significantly cheaper;
(Not sure if this is that much of a bad thing, though - it might depend on the project's context, i.e. if it is a quick dirty script or a robust project, and this pattern still needs to be explicitly stated through the `symbol##` syntax or similar.)

**Comment by technomancy** [comment]
> As far as I've understood, all symbols bound inside a macro's return
> body should be quoted, and I think that's a nice thing.

This isn't really accurate. You can bind symbols that come in as arguments with no trouble.

    (macro def-coroutine [name arglist ...]
      `(local ,name (coroutine.create (fn ,arglist ,...))))

Is that what you mean?

The only reason you need autogensym is when you introduce a new identifier that comes from inside quote.

**Comment by andreyorst** [comment]
@YohananDiamond is this what you're looking for?

``` clojure
(macro def-coroutine [name args ...]
  `(local ,name (coroutine.create (fn ,args ,...))))

(macro destructure-with-prefix [prefix seq ...]
  `(local ,(collect [_ thing (ipairs seq)]
             (values thing (.. (tostring prefix) "/" (tostring thing))))
     ,...))
```

These macros expand to

``` clojure
(local my-coroutine (coroutine.create (fn []
                                        (print 10)
                                        (coroutine.yield)
                                        (print 20))))

(local {thing1 "my-mod/thing1"
        thing2 "my-mod/thing2"}
  (require "my-mod"))
```

**Comment by YohananDiamond** [comment]
Oh ^^' I didn't know that - I think I misunderstood the purpose of `#` then.
And yes, @andreyorst, that's what I intended. Thanks!

One last thing, for curiosity - is there a way to bind a specific symbol inside the macro, then?
```clojure
(macro def-name []
  `(local fixed-name 10)) ; this errors out, as the symbol is not passed as an argument and isn't generated by autogensym
  
(def-name)
(assert (= fixed-name 10))
```

**Comment by andreyorst** [comment]
> One last thing, for curiosity - is there a way to bind a specific symbol inside the macro, then?

Yes:

``` clojure
(macro def-name []
  (let [name (sym :fixed-name)]
    `(local ,name 10)))

(macrodebug (def-name)) ;;=> (local fixed-name 10)
```

Note, however, that this break macro hygiene, and thus dangerous, as you can [accidentally capture a symbol](https://en.wikipedia.org/wiki/Hygienic_macro#The_hygiene_problem).

**Comment by andreyorst** [comment]
> Oh ^^' I didn't know that - I think I misunderstood the purpose of `#` then.

Here's how you can understand it. This macro defines a unique name and binds it to `10`:

``` clojure
(macro a []
  (let [a (gensym :a)]
    `(local ,a 10))) ;; => (local a_0_ 10)
```

`gensym` generates a unique name to avoid symbol capture. Exactly the same can be acheived with the autogensym shorthand `#`:

``` clojure
(macro a []
  `(local a# 10)) ;; => (local a_0_auto 10)
```

Note that no explicit `gensym` is needed here.

Recent updates in the compiler logic changed how autogensym works, and now each such name has `_auto` suffix, to allow gensyms and autogensyms share base name without name clash:

``` clojure
(macro m []
  (let [a (gensym :a)]
    `(let [,a 1
           a# 2]
       (+ ,a a#))))
;; =>
(let [a_0_ 1
      a_0_auto 2]
  (+ a_0_ a_0_auto))
```

The indexes will differ depending on surroundings to generate safe unique names.

Most of the time you won't be needing explicit `gensym` as `#` is almost always enough. This provides almost sound and hygiene macro system, but you can still make unhygienic macros, as shown in previous comment

**Comment by YohananDiamond** [comment]
Hmm... I think I got it. Thanks for the help!
