### ISSUE TITLE
Allow ... to be used in different places inside the lambda list of functions.

### ISSUE THREAD

**Issue by eko234** [bakpakin/Fennel#366]
I think it could be an interesting feature to be able to use the ... symbol to denote places between arguments in functions, like using
`(fn x [... last_arg] (print (.. "this is the las arg: " x)))` or `(fn y [first ... last] (print "you get the idea"))`, but I think it would make the `&` operator to feel kind of in a wierd place, it would be nice to have such ways of destructuring in such places, but that would be another feature/question i guess.

**Comment by technomancy** [comment]
It could be an interesting feature, but it's not one that we can implement.

The `...` feature is built-in to the Lua VM and isn't a feature of Fennel. If we tried to change its semantics (which are not great) we would lose the performance gains that it offers.

**Comment by eko234** [comment]
mm, I see, I guess I'm better off writting some kind of destructuring macro for that purpose, I'm indeed already writting a collection of macros, do you plan on adding a part on the repo/web-page to maybe list some fennel lib/utilities fennel users write? it would be nice to share and make these kind of libraries (specially macros) be more visible to other users.

**Comment by technomancy** [comment]
Sure; the list is here: https://github.com/bakpakin/Fennel/wiki/Codebases
