### ISSUE TITLE
Windows Defender finds `Win32/Uwamson.A!ml` malware in Windows binaries

### ISSUE THREAD

**Issue by ggandor** [bakpakin/Fennel#368]
![defender_fennel_exe2](https://user-images.githubusercontent.com/17800844/124299423-b2044d80-db5d-11eb-8ef1-c807230e0df8.JPG)
This seems to be a valid threat, not a false positive. I have tried all the ones above 0.9, with the same result. The Linux binaries seem fine, at least the most recent one.

**Comment by technomancy** [comment]
> This seems to be a valid threat

I don't understand what this means. Are you saying that fennel-lang.org was compromised and the binaries hosted on that site were replaced with versions containing malware?

**Comment by ggandor** [comment]
Oh, I meant `Win32/Uwamson.A!ml` seems to be some actual, potentially dangerous malware. 

> Are you saying that fennel-lang.org was compromised and the binaries hosted on that site were replaced with versions containing malware?

I guess...(?) I wanted to upgrade to 0.9.2, but was unable to execute it, access was denied immediately. It's the same with any of the Windows binaries that I download from fennel-lang.org now.

**Comment by technomancy** [comment]
> Oh, I meant Win32/Uwamson.A!ml seems to be some actual, potentially dangerous malware.

Sorry, that doesn't really make things any clearer. I have never heard of `Win32/Uwamson.A!ml` before; how is it related to Fennel?

What makes you think that this is not a false positive?

**Comment by ggandor** [comment]
> I have never heard of Win32/Uwamson.A!ml before; how is it related to Fennel? 

No idea, I haven't heard of it before either. I have found a more or less recent, related issue: https://github.com/clangen/musikcube/issues/436 This could be some false positive after all, but even if that is the case, the problem still persists, namely that the OS simply doesn't allow to run the .exe files now.

**Comment by technomancy** [comment]
Sure, OK. But I don't see how this is a problem with Fennel; it seems like an issue with your OS. Nothing much we can do on our side.

**Comment by ggandor** [comment]
I see, but the maintainer wrote in that linked issue that a Visual Studio update + recompilation solved the problem for them, so I thought maybe something could be done after all.

**Comment by technomancy** [comment]
OK, I see; maybe you can build from source and use that to work around your problem.

**Comment by technomancy** [comment]
I had to upload a new version to fix an unrelated issue with #351 so you can see if it still flags the new version.

**Comment by ggandor** [comment]
The new version of 0.9.2 works, it's not flagged anymore. Thank you for your assistance!
