### ISSUE TITLE
Test failure on 5.4 when matching error message

### ISSUE THREAD

**Issue by mrichards42** [bakpakin/Fennel#372]
This test fails for me on 5.4, since it's matching on a particular error message that appears to have changed:

https://github.com/bakpakin/Fennel/blob/2e0ce2e21198a6aae1b2fc8d7e4b8a7d7d3ab11b/test/core.fnl#L146

```
(fn b [] (each [e {}] (e))) (let [(_ e) (pcall b)] (e:match \":[1]: .*\"))
;; on versions < 5.4
:1: attempt to call a table value
;; on 5.4
:1: for iterator 'for iterator' is not callable (a table value)
```

**Comment by technomancy** [comment]
Hm; I can't reproduce this on 5.4.2, but anyway it's easy to tweak. Updated with a string that matches what you're seeing above.

**Comment by mrichards42** [comment]
Ah, I'm on 5.4.3, looks like that was changed [here](https://github.com/lua/lua/commit/4bd10b6fe81c0a56eb9e01e24fba10e655966870)
