### ISSUE TITLE
Proposal: Add comment reader macro for S-Expression

### ISSUE THREAD

**Issue by glyh** [bakpakin/Fennel#376]
In Clojure, we can comment out a block of S-Expression like this:
```clj
#_(prn 1 2 3)
```
Which is really handy for testing codes. It will be great if we have this way to comment codes. 

Take vim for example. 

Using comment macro, I've got to press these keys: "ysa((  acomment\<Esc>". But with this reader macro, I can only press "i#_\<Esc>“. It also reduce the brackets you'll see in the exsiting codes.

**Comment by technomancy** [comment]
> It also reduce the brackets you'll see in the exsiting codes.

Hm; is this really true? Seems like `#_(prn 1 2 3)` and `(comment prn 1 2 3)` are equivalent in brackets. It's just the difference between one token before the delimiter vs one token after.

**Comment by sogaiu** [comment]
Sorry, not directly related perhaps...

Oh interesting -- hadn't occurred to me to insert `comment` at the beginning of lists.  I had been wrapping things with `(comment` and `)`.

This works nicely for multiline things that happen to be lists.

Thanks for mentioning the idea.

On a tangential note, I've seen a single quote used in front of top-level lists in some emacs lisp code for a similar effect.

**Comment by glyh** [comment]
> > It also reduce the brackets you'll see in the exsiting codes.
> 
> Hm; is this really true? Seems like `#_(prn 1 2 3)` and `(comment prn 1 2 3)` are equivalent in brackets. It's just the difference between one token before the delimiter vs one token after.

Yeah they are, but the in first one you don't have to insert the right paren, which can be annoying sometimes.

**Comment by glyh** [comment]
> Sorry, not directly related perhaps...
> 
> Oh interesting -- hadn't occurred to me to insert `comment` at the beginning of lists. I had been wrapping things with `(comment` and `)`.
> 
> This works nicely for multiline things that happen to be lists.
> 
> Thanks for mentioning the idea.
> 
> On a tangential note, I've seen a single quote used in front of top-level lists in some emacs lisp code for a similar effect.

It's similar but the value result from the expressions are differenet. But I think "nil" seems to be safer than list of codes.

**Comment by sogaiu** [comment]
If "resulting value" is of concern...

IIRC, in Clojure `#_` and the appropriate thing [1] that follows it are just discarded.  It doesn't result in anything, not even `nil`.

`(comment ...)` results in `nil`, which I presume is often not what one wants when the `...` is originally part of some other "expression", i.e. `...` is not at the top-level.

---

[1] Thing that can be "read".

**Comment by andreyorst** [comment]
My favorite use of `#_` in Clojure is in `let` blocks that do succession of transformations of a value, that I'd want to quickly instrument:

```clojure
(let [a (foo)
      _ (prn a)
      a (bar a)
      _ (prn a)
      a (baz a)
      _ (prn a)]
   ;; use a
 )
```

Removing these prints is just a matter of adding `#` in front of each `_`, because Clojure allows spaces between reader forms:

```clojure
(let [a (foo)
      #_ (prn a)
      a (bar a)
      #_ (prn a)
      a (baz a)
      #_(prn a)]
   ;; use a
 )
```

This is super handy. Though this can be done with `comment` as easilly, but with much more typing:

```clojure
(let [a (foo)
      _ (comment prn a)
      a (bar a)
      _ (comment prn a)
      a (baz a)
      _ (comment prn a)]
   ;; use a
 )
```

This requires 24 keypresses versus 3 keypresses if just inserting `#` :slightly_smiling_face:

**Comment by sogaiu** [comment]
Cool use!

**Comment by technomancy** [comment]
The main problem with this is that we have already overloaded the `#` character to mean two things: it's the length operator but also `hashfn` shorthand. So I think introducing a third meaning for it would be confusing, on top of the inherent ambiguity in the grammar.

**Comment by glyh** [comment]
> Sorry, not directly related perhaps...
> 
> Oh interesting -- hadn't occurred to me to insert `comment` at the beginning of lists. I had been wrapping things with `(comment` and `)`.
> 
> This works nicely for multiline things that happen to be lists.
> 
> Thanks for mentioning the idea.
> 
> On a tangential note, I've seen a single quote used in front of top-level lists in some emacs lisp code for a similar effect.

I've tried quoting in fennel, but since it's compiled down to lua, it complains symbols can only be used in compile time.

**Comment by glyh** [comment]
> The main problem with this is that we have already overloaded the `#` character to mean two things: it's the length operator but also `hashfn` shorthand. So I think introducing a third meaning for it would be confusing, on top of the inherent ambiguity in the grammar.

That doesn't matter, maybe we can use other operators... for example "$_" or something else.

**Comment by andreyorst** [comment]
> That doesn't matter, maybe we can use other operators... for example "$_" or something else.

`$` is used to represent parameters in `hashfn`, and we don't have that many free characters that are reserved in identifiers.

Besides the character overload, there is one more thing that makes implementation of `#_` harder - consecutive ignore-forms are stacked in Clojure:

``` clojure
(def a #_#_#_#_#_ 1 2 3 4 5 6) ; a is 6
(def b #_#_ 1 #_#_ 2 #_ 3 4 5) ; can you guess what's the value of b?
```

I can easily imagine, that if we don't implement this feature, it will be quickly requested :)

> The main problem with this is that we have already overloaded the # character to mean two things: it's the length operator but also `hashfn` shorthand. 

@technomancy I've thought that the `#` length operator was deprecated. If not, maybe it's good time to do that? We have `length` which is much more common. (*Imagining `#_#(# $)`*)

On a side note, there's a [parser macro proposal](https://github.com/bakpakin/Fennel/wiki/ParserMacros), which may be used to implement `ignore-form` macro, I guess. Maybe this direction can be explored.

**Comment by technomancy** [comment]
> I've thought that the # length operator was deprecated. If not, maybe it's good time to do that? We have length which is much more common. (Imagining #_#(# $))

It's true it's deprecated, but it's not causing any trouble where it is, so I don't think that removing it is helpful. In this case really it's the hashfn syntax which causes the conflict.

> That doesn't matter, maybe we can use other operators... for example "$_" or something else.

The point of using an existing notation is we can point existing tools (text editors, syntax highlighters, etc) to the Clojure support and get it working basically for free. If we diverge and create our own unique syntax then we add overhead to every single piece of tooling and make it just a little more difficult to support Fennel.

Of course, there are situations where that's justified. But when we already have two forms of comments, to talk about adding a third, I don't think it's one of those situations.
