### ISSUE TITLE
Support to declare "mixed" fennel tables

### ISSUE THREAD

**Issue by eko234** [bakpakin/Fennel#377]
I'm using leafo's lapis web framework with fennel and I found a function that expects me to pass a table of the form:

`{"posts", has_many = "Posts"}`

It works well with 

`{:1 "posts" :has_many "Posts"}`

so, is there a more neat way to handle these situations, or a way to express a "mixed" table in fennel that is more "lua" like?

**Comment by eko234** [comment]
well, indeed it turns out it didn't work at all, I also tried using the lua function to return a string with the table as I needed it but that wont work either.

**Comment by technomancy** [comment]
> so, is there a more neat way to handle these situations, or a way to express a "mixed" table in fennel that is more "lua" like?

No, this is intentionally not supported. For clarity's sake, sequential and key/value tables are visually distinct from each other.

**Comment by andreyorst** [comment]
> {:1 "posts" :has_many "Posts"}
>
> so, is there a more neat way to handle these situations, or a way to
> express a "mixed" table in fennel that is more "lua" like?
>
:1 is a string "1". To define a mixed table you can directly use integer
keys:

{1 "posts" :has_many "Posts"}

Or use a tset/table.insert

(doto {:has_many :Posts}
  (table.insert :posts))

Alse, see https://github.com/bakpakin/Fennel/issues/353

>

**Comment by eko234** [comment]
Thanks, I'll check if that works tomorrow, also, thats a neat macro.

**Comment by eko234** [comment]
> {:1 "posts" :has_many "Posts"} so, is there a more neat way to handle these situations, or a way to express a "mixed" table in fennel that is more "lua" like?
> :1 is a string "1". To define a mixed table you can directly use integer keys: {1 "posts" :has_many "Posts"} Or use a tset/table.insert (doto {:has_many :Posts} (table.insert :posts)) Also, see #353

It worked, thanks.
