### ISSUE TITLE
Macros expanding to invalid fennel

### ISSUE THREAD

**Issue by eko234** [bakpakin/Fennel#382]
I have this macro, might not be the prettiest of them all, but when i compile it, it seems to expand to something with unbalanced parens, I will provide the expansion soon.
```
(fn or! [body error_state]
  `(match 
    [(pcall
     #(do
       ,body))]
    [false message#] (error (->> message# ,error_state) 0)
    [true maybe_value# maybe_message#] (match
                                        [maybe_value# maybe_message#]
                                        [nil message#] (error (->> message# ,error_state) 0)
                                        [value# _#] value#)
    _# (error "THIS SHOULD NEVER HAPPEN")))
```

**Comment by andreyorst** [comment]
the pcall here is wrapped into a table but it doesn't have to, you can match on mulitple values with parentheses. You then check the `[true maybe_value# maybe_message#]` branch in a nested match to have a non nil value in a `maybe_value#` variable, but if it is nil you will never get to that match, as the pattern `[true maybe_value# maybe_message#]` will simply don't match. If nils can be in this case, prepend `?` to variable names that can be nil. Here's a fixed macro:

```fennel
(fn or! [body error_state]
  (let [_ (sym :_)]
    `(match (pcall #(do ,body))
       (false message#) (error (->> message# ,error_state) 0)
       (true ?maybe_value# ?maybe_message#) (match [?maybe_value# ?maybe_message#]
                                              [nil message#] (error (->> message# ,error_state) 0)
                                              [value#] value#
                                              ,_ (error "no value and no message" 0))
       ,_ (error "THIS SHOULD NEVER HAPPEN"))))
```

Not sure if it's good that `error_state` is evaled several times

**Comment by eko234** [comment]
> the pcall here is wrapped into a table but it doesn't have to, you can match on mulitple values with parentheses. You then check the `[true maybe_value# maybe_message#]` branch in a nested match to have a non nil value in a `maybe_value#` variable, but if it is nil you will never get to that match, as the pattern `[true maybe_value# maybe_message#]` will simply don't match. If nils can be in this case, prepend `?` to variable names that can be nil. Here's a fixed macro:
> 
> ```fnl
> (fn or! [body error_state]
>   (let [_ (sym :_)]
>     `(match (pcall #(do ,body))
>        (false message#) (error (->> message# ,error_state) 0)
>        (true ?maybe_value# ?maybe_message#) (match [?maybe_value# ?maybe_message#]
>                                               [nil message#] (error (->> message# ,error_state) 0)
>                                               [value#] value#
>                                               ,_ (error "no value and no message" 0))
>        ,_ (error "THIS SHOULD NEVER HAPPEN")))) ; this will happen if pcall somehow returns false without a message
> ```
> 
> Not sure if it's good that `error_state` is evaled several times

Oh thanks , I will try out when I get home.

**Comment by andreyorst** [comment]
Further simplification:

``` fennel
(macro or! [body error_state]
  (let [_ (sym :_)]
    `(match (pcall #(do ,body))
       (true value#) value#
       (where (or (false message#)
                  (true nil message#)))
       (error (->> message# ,error_state) 0)
       ,_ (error "THIS SHOULD NEVER HAPPEN"))))
```

**Comment by eko234** [comment]
Well I think is my fault for not being clear, what I'm trying to do is to capture what could be:
1) the two values returned as the result of pcall
2) check if the second "value" is really a double value return and then match agains that pattern

**Comment by eko234** [comment]
```
(fn or! [body error_state]
  (let [_ (sym :_)]
    `(match (pcall #(do ,body))
       (true value#) value#
       (where (false message#))
       (error (->> ,error_state) 0)
       (where (or (false message#)
                  (true nil message#)))
       (error (->> message# ,error_state) 0)
       ,_ (error :!))))
```
this is what I needed, thank you so much.
