### ISSUE TITLE
A function cannot use another function defined behind it

### ISSUE THREAD

**Issue by 6cdh** [bakpakin/Fennel#385]
**Description**

A function cannot use another function defined behind it. Like C/C++. While Lua can. Is it a bug or feature?

**Reproduce**

```fennel
;; f.fnl
(fn f1 []
  (f2))

(fn f2 []
  1)
```

Run this code:

```shell
$fennel f.fnl
Compile error in f.fnl:3
  unknown global in strict mode: f2

  (f2))
   ^^
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.f2 if you really want a global.
* Try moving this code to somewhere that f2 is in scope.
* Try binding f2 as a local in the scope of this code.
```

**Info**

* Fennel version: Fennel 0.10.1-dev commit id [#50dfc7f](https://github.com/bakpakin/Fennel/tree/50dfc7f5bbde462c31b587028a3952a5333aab9e)

**Comment by technomancy** [comment]
Yes, it's very intentional that functions use lexical scope. Lua functions use globals by default, but good Lua code avoids this and declares all functions as local.

**Comment by 6cdh** [comment]
My Bad. I thought it works in Lua. In Lua, function `f1` uses a global `f2` (undefined) rather than local `f2` defined behind `f1` without any warning.

In fact, my full fennel code is

```fennel
(fn flt_eq? [flt1 flt2]
  (-> (- flt1 flt2) (math.abs) (< 1e-06)))

(fn all [pred tbl]
  (each [k v (pairs tbl)]
    (if (not (pred v k)) (lua "return false")))
  true)

(fn subset? [tbl1 tbl2]
  "Is `tbl1` a subset of `tbl2`?"
  (all (fn [v k]
         (eq? (. tbl2 k) v)) tbl1))

(fn tbl_eq? [tbl1 tbl2]
  (and (subset? tbl1 tbl2) (subset? tbl2 tbl1)))

(fn eq? [v1 v2]
  (match [(type v1) (type v2)]
    [:number :number] (flt_eq? v1 v2)
    [:table :table] (tbl_eq? v1 v2)
    _ (= v1 v2)))
```

It can't work because I use `eq?` in function `subset?`. Is my only option is defining these subprocedures in `eq?`. In this way, I can't reuse these subprocedures in other functions.

**Comment by andreyorst** [comment]
you can use forward declaration:

```fennel
(fn flt_eq? [flt1 flt2]
  (-> (- flt1 flt2) (math.abs) (< 1e-06)))

(fn all [pred tbl]
  (each [k v (pairs tbl)]
    (if (not (pred v k)) (lua "return false")))
  true)

(var eq? nil)             ; forward declare `eq?` to use in `subset?` 

(fn subset? [tbl1 tbl2]
  "Is `tbl1` a subset of `tbl2`?"
  (all (fn [v k]
         (eq? (. tbl2 k) v)) tbl1))

(fn tbl_eq? [tbl1 tbl2]
  (and (subset? tbl1 tbl2) (subset? tbl2 tbl1)))

(set eq? (fn [v1 v2]
           (match [(type v1) (type v2)]
             [:number :number] (flt_eq? v1 v2)
             [:table :table] (tbl_eq? v1 v2)
             _ (= v1 v2))))
```

**Comment by 6cdh** [comment]
@andreyorst Thanks. It works though a little ugly :)

**Comment by technomancy** [comment]
Other ways to solve this, though `var` is probably best in this case:

1. Put all the functions in a table; then only the table needs to be in scope.
2. Pass the latter function as an argument to the earlier function.
3. Of course you can define it as a global like in lua with `(fn _G.whatever [] ...)` but this is bad and I mention it only for completeness sake. =)
