### ISSUE TITLE
Is there a spec for Fennel?

### ISSUE THREAD

**Issue by alexaandru** [bakpakin/Fennel#388]
First of all, apologies for creating an issue to ask a question. Would you consider enabling "Discussions" feature in your repo, so that questions can be asked there instead?

Now to the actual Q: as the $subj states, looking for a spec.

I see the `Reference` as the closest thing to a spec, however it does not even address naming of identifiers. The `Tutorial` instead, has a brief description of identifiers: https://fennel-lang.org/tutorial#functions-and-lambdas however it does not give an exhaustive description for the set of characters that can compose an identifier, just some examples.

Are all UTF-8 characters accepted as identifier? For example ⧔, ⧕ or ∫? I know they work because I used them :-) but was that intentional, is it part of the spec, or an accident and may be removed in the future? I already get warnings from Hotpot about `&` possibly being forbidden as an identifier in the future.

The brief note says that _"..., but must start with a letter or underscore."_ yet, math symbols are not exactly letters, are they?

And once again, thank you for this language!
The more I use it, the more fun it is!! :) Love it! :)

Cheers!

**Comment by alexaandru** [comment]
> > First of all, apologies for creating an issue to ask a question. Would you consider enabling "Discussions" feature in your repo, so that questions can be asked there instead?
> 
> No problem discussing here. I don't want to enable GitHub's discussion since it would be redundant with the mailing list, but issues are fine for this.

Great then, thank you :-)
 
> The reference should function as a spec, but admittedly it is incomplete, simply because we haven't put the work in yet. This is something we should remedy.

> > Are all UTF-8 characters accepted as identifier?
> 
> I need to take a closer look at the UTF-8 spec, but speaking as to the implementation, anything outside the ASCII range should be treated the same. I don't want to commit to this in the reference though, since there are many characters which should not be used in identifiers but today (such as whitespace characters) they are because we are not UTF-savvy enough to tell the difference. So letters, punctuation, marks, symbols, and numbers should all be documented as acceptable, but we should not claim to support separators and control characters.

Thank you, this is very helpful.
 
> > The brief note says that "..., but must start with a letter or underscore." yet, math symbols are not exactly letters, are they?
> 
> You're right; this is incorrect. The intent is that they must not start with a number.
> 
> If you want to put together a patch to clarify this, that'd be great. Otherwise I'll get to it eventually...

Sure, I can give it a try, starting from the above clarification.

Cheers!

**Comment by technomancy** [comment]
> Otherwise I'll get to it eventually...

Well, it's eventually now. I've added details about the accepted syntax in b93f6c9. Does that cover the questions you had?

**Comment by alexaandru** [comment]
Looks great, it sure does. Thank you! :)
