### ISSUE TITLE
Repl printing

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#39]
While I agree that Fennel shouldn't require a pretty-printer, I wonder if it would be helpful to set up the default repl that you get with the executable `fennel` script with something better than `table: 0x55a8c7165b00`.

I wrote a fennel-specific pretty-printer that's 128 lines; and I've been using it in the repl via a `.fennelrc` of such:

```lisp
(set options.pp ((. (require "fennel") "dofile") "/home/phil/src/fennelview/fennelview.fnl"))
```

Should we include this and load it up in the default repl? https://gitlab.com/technomancy/fennelview

(Also, I have some generative testing in that repo that might be handy for other fennel-related tests if anyone is curious.)

**Comment by bakpakin** [comment]
Looks good! I think it would make sense to include that in fennel.lua. The original pretty printer was removed as I was upgrading to the new compiler as it was not modular and part of the compiler, but for the repl the pretty printer is useful.

I also looked the code and noticed the string parsing bug. I have fixed escape handling a pushed a fix.
