### ISSUE TITLE
Threading macro ->> calls functions in incorrect order

### ISSUE THREAD

**Issue by BrainDamagedCoder** [bakpakin/Fennel#399]
The ->> threading macro's internal implementation uses the function pairs instead of ipairs (which is what the -> threading macro uses) to iterate through the functions that were passed in, because the pairs function returns keys and values in a arbitrary order, the functions are called in incorrect order.
example:
```
(fn print-one [_] 
  (io.write "one ") 
  _)

(fn print-two [_] 
  (io.write "two ") 
  _)

(fn print-three [_] 
  (io.write "three ") 
  _)

(->> nil print-one print-two print-three)
```
In this case, the functions are called in reverse order i.e., prints `three two one` instead of the expected `one two three`.

**Comment by andreyorst** [comment]
I've tried, and can't reproduce that, can we get a bit more details, like what Lua implementation are you using, what fennel version is that, and so on?

Also, I've thought that `pairs` on sequential tables walks in the exact order, and only associative part gets mixed up depending on hashing.

**Comment by technomancy** [comment]
For some reason I always get the same order with `pairs` as `ipairs` but you are right that this isn't guaranteed by the manual. Will go ahead and change this; thanks for catching it.
