### ISSUE TITLE
Backslash in a string

### ISSUE THREAD

**Issue by zbouslikhin** [bakpakin/Fennel#407]
Hi all,

I'm trying to convert such lua code to Fennel, but have few problems:
```lua
vim.api.nvim_buf_set_keymap('n', 't', '<esc>', [[<C-\><C-n>]])
```

- First problem is related with the backslash. I'd think to write a single backslash, something like this is needed:
```
(print "\\") ;returns double \\ instead of \ in lua
```
- Second problem is related with `[[<C-\><C-n>]]`. How would that be written in fennel?

**Comment by andreyorst** [comment]
This works like in most other languages, the backslash needs to be escaped by another backslash in double quotes:

```fennel
(vim.api.nvim_buf_set_keymap :n :t :<esc> "<C-\\><C-n>")
```

> * First problem is related with the backslash. I'd think to write a single backslash, something like this is needed:
> 
> 
> ```
> (print "\\") ;returns double \\ instead of \ in lua
> ```

I'm not sure, but if that's the case, there might be a bug somewhere. On my machine this works as expected:

![image](https://user-images.githubusercontent.com/19470159/145679892-0688f9bd-d28c-4c20-9830-21446330f8de.png)

Tip: you can use https://fennel-lang.org/see when you're unsure how to convert something from Lua to Fennel and vice versa.

**Comment by zbouslikhin** [comment]
Thanks a lot.
Using the link to convert fennel to lua (and also locally on my machine), `(print "\\")` is converted to double backslash 
![Screenshot_2021-12-11-15-29-37-782_com mi globalbrowser_1](https://user-images.githubusercontent.com/47977073/145680295-7f9e40ad-76f5-4910-be0a-b01e98ac2f8d.jpg)

**Comment by andreyorst** [comment]
Yes, Fennel treats strings a bit differently from Lua, but in a more conventional way, similar to most other languages. There are no `[[]]` strings in Fennel, only `""` ones (and colon strings, which are strings with no spaces, like `:this` is essentially the same as `"this"`). And in `""` strings you need to backslash special characters, like backslash itself.

@technomancy, I think we might want to add a more explicit section explaining differences in strings in Fennel and Lua in the manual/reference.

**Comment by technomancy** [comment]
@zbouslikhin The basic case of `"\\"` is one where the exact same notation is used between Fennel and Lua, so the result you pasted is expected. The string in question contains a single backslash character, as you can see:

    (length "\\") ; -> 1

I'm all for clarifying the docs but I think in this case I am having a hard time understanding what's causing the confusion. I could use some concrete suggestions for how to make it clearer.

As far as I can tell for the original question, pasting `vim.api.nvim_buf_set_keymap('n', 't', '<esc>', [[<C-\><C-n>]])` into https://fennel-lang.org/see does give the correct result.

**Comment by technomancy** [comment]
I'm going to close this since it doesn't seem like there's anything else to do here, but I'm still open to suggestions for how to clarify if anyone has them.
