### ISSUE TITLE
Error when compiling: (import-macros {: packagestrip} :macros)

### ISSUE THREAD

**Issue by HenrikBach1** [bakpakin/Fennel#409]
Hi

I ask above/below question here, due to that no one answers my question in original package repo, however, I believe it is a Fennel related problem/issue:

When compiling the toAPK tool with `make compile-lua` given in the README.md, I get this error:

```
Compile error in src/toAPK.fnl:10
  Compile error in src/fennel/macros.fnl:254
  macros module not found.

...

(import-macros {: packagestrip} :macros)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

An equivalent error rises when trying to use Fennel directly.

What am I doing wrong or missing?

Thank you.

**Comment by andreyorst** [comment]
Is this module in the macro path? You can check your macro path with:

```fennel
>> (local fennel (require :fennel))
>> fennel.macro-path
"./?.fnl;./?/init-macros.fnl;./?/init.fnl"
```

You can add modules with the key `--add-macro-path`.

**Comment by durrendal** [comment]
It looks like andreyorst was spot on, the makefile was missing a --add-macro-path call, when toAPK was written that wasn't necessary, and I failed to update the Makefile to accommodate it.

You can compile it to lua with this:
fennel --compile src/toAPK.fnl --add-macro-path src/macros.fnl > src/toAPK.lua

I've updated the issue on the official repo with this information as well and will push a fix for it soon.

**Comment by technomancy** [comment]
Gonna go ahead and close this out then; looks like it's resolved?
