### ISSUE TITLE
fennel.compileString under a read-only environment

### ISSUE THREAD

**Issue by sherief** [bakpakin/Fennel#410]
I'm deploying Lua / Fennel in a setup where, after initialization, global environment / upvalues are made read only at the VM level, by preventing OP_SETTABUP instructions from executing (details and patch can be found [here](https://listmaster.pepperfish.net/hyperkitty/list/lua-l@lists.lua.org/thread/VS6J5OBNWDVHY34PIILVBXSSCJPBKE5J/))

Trying to call `compileString` with the environment locked leads to an error, and the offending line is the last line in this block:

```
  root = {chunk = nil, options = nil, reset = _1_, scope = nil}
  root["set-reset"] = function(_2_0)
    local _3_ = _2_0
    local chunk = _3_["chunk"]
    local options = _3_["options"]
    local reset = _3_["reset"]
    local scope = _3_["scope"]
    root.reset = function()
      root.chunk, root.scope, root.options, root.reset = chunk, scope, options, reset
      return nil
    end --This is the offending line reported
    return root.reset 
```

I'm trying to understand why this is modifying the global env but I'm a bit lost. Any pointers that can help with this? Is compiling Fennel to Lua under this situation possible? I can always workaround by doing the Fennel --> Lua compilation in a separate VM and read back the chunk, but that's less than ideal.

**Comment by technomancy** [comment]
Right before the line you listed, you can see it declares `local root`. So that code does not in fact make any changes to the global environment.

Perhaps the error message is pointing to the wrong place. If you have a repro case it might help investigate.

It's certainly possible to call `compileString` without modifying the environment, as evidenced by this snippet:

```
(setmetatable _G {:__newindex (fn [] (error :strict-mode!))})
(local fennel (require :fennel))
(fennel.compileString "(fn [])")
```

**Comment by sherief** [comment]
Thanks a lot for confirming. I'll try to build a standalone repro and debug further.

**Comment by technomancy** [comment]
Might cut a release soon, so if you have any info to share about this problem, now would be good.

**Comment by sherief** [comment]
I'll work on it this weekend, sorry for the delays.

**Comment by technomancy** [comment]
Going to close this out since it's not actionable as-is, but we can reopen if more details are provided.
