### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [bakpakin/Fennel#412]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/753) to add `fennel-bin` to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for fennel for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by technomancy** [comment]
Cool.

1. It's probably best to keep packaging out of this repo and in a downstream location.
2. The documentation about package managers is kept on the wiki, so it's free for anyone to update when new package managers add Fennel: https://github.com/bakpakin/Fennel/wiki/Packaging However, the linked pull request doesn't look right. It's just downloading the x86_64 binary regardless of the architecture of the user. If you want to make a single package that works for everyone, it's better to just get the script version and add a dependency on Lua. If you really want a binary for some reason, you'll need to offer one for each supported architecture, but in the context of a package manager there's really not any benefit to the binary version.

**Comment by wizard-28** [comment]
> It's probably best to keep packaging out of this repo and in a downstream location.

Okay!

---

> However, the linked pull request doesn't look right. It's just downloading the x86_64 binary regardless of the architecture of the user. If you want to make a single package that works for everyone, it's better to just get the script version and add a dependency on Lua

We only support `x86_64` at the moment, We have plans for other architectures in the next version. I would just add the `-bin` pacscript for now, and update it with multi architecture support in the future.

I'm making a variant package with the fennel script, which one do you want us to add to the wiki? I guess the latter for now.

**Comment by technomancy** [comment]
OK cool; sounds good.

**Comment by technomancy** [comment]
Oh, I also noticed that the packaging doesn't seem to do any verification of the checksum or signature; that looks like a pretty major oversight too.
