### ISSUE TITLE
Typo in the Wiki page

### ISSUE THREAD

**Issue by metafates** [bakpakin/Fennel#436]
Hello! Looks like there's a typo in the [Wiki runtimes page](https://github.com/bakpakin/Fennel/wiki#lua-runtimes)
Which one is valid? They point to the same repository https://github.com/yuin/gopher-lua/
I tested it myself and looks like fennel works just fine with it

![Screenshot 2022-12-16 at 23 20 56](https://user-images.githubusercontent.com/62389790/208182904-a0bcaca4-cb96-424e-9248-49a263817be2.png)

**Comment by technomancy** [comment]
Good catch! The bugs in gopher-lua got fixed, but the wiki update didn't catch this.

(There is still one bug that prevents Fennel's own test suite from passing, but it shouldn't affect very many Fennel programs: https://github.com/yuin/gopher-lua/issues/417)
