### ISSUE TITLE
Official logo/devicon

### ISSUE THREAD

**Issue by Grazfather** [bakpakin/Fennel#438]
I use fennel a lot, and I use neovim (and I use fennel to configure my neovim :) ), and I use devicons to show file types and such.

The devicon for fennel is just some moon emoji: 🌜 

I hate it.

Have you considered adding a logo to the font? I don't know if you have an 'official' logo, though I do like the one on fennel-lang.org
![image](https://user-images.githubusercontent.com/497310/215276633-e9945f75-c421-4ab5-ae9b-e365df8243c0.png)

**Comment by technomancy** [comment]
Yep, that's the official logo.

I'm not sure what "add a logo to the font" means, but it occurs to me that we don't have a clear license and copyright declared for the logo, which was created by @m455. This is an oversight. If they could clarify whether it's OK to license it as CC-BY-SA or some other CC license, then that would clarify things for other people who want to use it in neovim or whatever.

**Comment by Grazfather** [comment]
Well [nerd fonts](https://www.nerdfonts.com/) patch fonts by adding extra glyphs for things like powerline and special icons and stuff. [dev icons](https://github.com/vorillaz/devicons) are where the logos and stuff live. I am not sure what the process would be to get your logo added, but if the logo were released and you were amenable to it, I could try to work on it.

**Comment by technomancy** [comment]
OK cool, I've just gotten confirmation that CC-BY-SA 4.0 is the license to use here, so I'll go ahead and update the repo. In the mean time, feel free to incorporate this into the font or whatever other tools you want, provided it's compatible with the license. Thanks.

**Comment by Grazfather** [comment]
Cool. Do you have the vector assets?

**Comment by Grazfather** [comment]
This was merged in FYI. https://github.com/ryanoasis/nerd-fonts/pull/1129
