### ISSUE TITLE
fennel.searcher "fennel.lua:1366: attempt to index a string value (local 'options')"

### ISSUE THREAD

**Issue by cnasc** [bakpakin/Fennel#44]
My environment: Lua 5.3.4 on MacOS 10.13.3

`fennel.searcher` returns a function that takes an options table, then calls `fennel_dofile` with the filename and the options. However, `require` passes the name of the module rather than options. 

https://github.com/bakpakin/Fennel/blob/1c46182e5838f5d4e9885fe5c39074b68b0f7fba/fennel.lua#L1361-L1368

So for example, when I run:
```
;; File: require-test.fnl
;; Env: fennel.lua and helpers.fnl are in same directory

(set fennel (require :fennel))
(table.insert package.searchers fennel.searcher)
(set helpers (require :helpers))
```

`fennel_dofile` ends up being called like `fennel_dofile("./helpers.fnl", "helpers")`. This results in an error when the code tries to set `options.filename`, so the require fails. This may be due to a difference in the way `require` works in Lua 5.1 and in 5.2+.

From the Lua 5.1 manual:
> Once a loader is found, require calls the loader with a single argument, modname.

From the Lua 5.2 manual (same in 5.3):
> Once a loader is found, require calls the loader with two arguments: modname and an extra value dependent on how it got the loader. (If the loader came from a file, this extra value is the file name.)

That said, I'm a bit puzzled because it seems from those descriptions that the loader will always be called with a string value, so it should also error on 5.1. (Just assuming that it works on 5.1 because the package.loaders used in the documentation becomes package.searchers in 5.2+)

**Comment by technomancy** [comment]
Ah, I see what's going on here. 5.1 just passes nil there, so it gets
treated as a nil options table, but if it changed in 5.2 then we need to
do it differently.

I wanted to give ~/.fennelrc access to the options table so it could
install its own pretty-printer, etc. But I think dofile and eval really
need to support passing on their arguments to the underlying code as
... args. I think I can use that instead to get the effect I want.

**Comment by lzhou** [comment]
"[[" and "[=[" cannot be used to quote multi-line strings in Fennel, as it's used for array notation.  Double quote seems to support multi-line strings.  This is great.

Is it possible to make single quote behave as Lua's "[[" does in Fennel?  I.e.: Backslash is used without escaping when quoted in single quotes?  For example: "\\" prints a single backslash, and so does '\'?  This feature is highly desirable when Fennel is used to compose text output that has a large number of backslashes.

**Comment by technomancy** [comment]
I would be hesitant to use single-quote for this since its meaning in every other lisp is dramatically different; it's usually not used in open/close pairs.
