### ISSUE TITLE
Strict globals forbid correct code

### ISSUE THREAD

**Issue by anuvyklack** [bakpakin/Fennel#441]
When I try to compile next code, I get an error: `unknown identifier in strict mode: handle`

```fennel
(let [(handle pid) (uv.spawn cmd {} (fn [code signal]
                                      (handle:close)))]
  ...)
```

however when I compile it with `--globals "*"` flag I get correct code:

```lua
local handle, pid = nil, nil
local function _10_(code, signal)
  handle:close()
end
handle, pid = uv.spawn(cmd, {}, _10_)
```

An alternative way is to create the variables before, but that looks ugly.
```fennel
(var (handle pid) (nil nil))
(set [(handle pid) (uv.spawn cmd {} (fn [code signal]
                                      (handle:close)))])
```

**Comment by technomancy** [comment]
I don't know if I understand what you're saying about `--add-macro-path` affecting the globals behavior; could you clarify about that? If you could provide an example which demonstrates the problem, it would be helpful.

**Comment by technomancy** [comment]
I'm going to close this because we're tracking the underlying issue already in #299 but it sounds like you might have another separate issue; if so feel free to open a new issue report with a description of the problem. Thanks.
