### ISSUE TITLE
REPL doesn't store `gensym`'ed variables?

### ISSUE THREAD

**Issue by KPCCoiL** [bakpakin/Fennel#480]
Suppose I have `foo.fnl`:
```fennel
(local foo (gensym))

(print foo)

(fn initialize []
  `(local ,foo 10))

(fn show []
  `(print ,foo))

{: initialize : show}
```
and `bar.fnl`:
```fennel
(import-macros {: initialize : show} :foo)

(initialize)
(show)
```

`fennel bar.fnl` prints
```
_1_
10
```
as expected.

However, when I try it in the REPL,  calling `initialize` sets `_1_` to `nil`, not 10. Weirdly, if I `initialize` twice, it becomes 10.
```
Welcome to Fennel 1.4.2 on PUC Lua 5.4!
Use ,help to see available commands.
>> (import-macros {: initialize : show} :foo)
_1_
nil
>> (initialize)
nil
>> (show)
nil

>> _1_
nil
>> (initialize)
nil
>> (show)
10

>> _1_
10
>>

```

The issue does not arise if you replace `(gensym)` in `foo.fnl` by `(sym :test)` (hence the title).

**Comment by KPCCoiL** [comment]
Thanks for your response. It's okay if it is intentional, and I'm closing this.

I was just playing around with fennel macros and trying to make something like
```fennel
(module) ; => (local _1_ {})

(local foo 10)
(export foo) ; => (tset _1_ "foo" foo)

(exports) ; => _1_
```

Actually, I realized similar functionality can be achieved without this sort of `gensym`s:
```fennel
(module
  (export foo)
  (local foo 10))
; => (do (local foo 10) {:foo foo})
```
I doubt if this is advised in the spirit of fennel though.

**Comment by technomancy** [comment]
I see what you mean. Yes, you could build that out, and it would work fine right until you try to do it from the repl. But it's better to use the Lua module system since it's much more transparent. There's only so much we can do to work around Lua's limitations with scope and chunks.
