### ISSUE TITLE
The REPL on https://fennel-lang.org/ fails to load with `[sprintf] unexpected placeholder`

### ISSUE THREAD

**Issue by missblit** [bakpakin/Fennel#485]
The REPL on https://fennel-lang.org/ fails to load with `[sprintf] unexpected placeholder`

Steps to reproduce:

1. Open https://fennel-lang.org/ in Firefox or Chrome
2. Observe that the REPL near the top of the page makes it to 99% but then gets stuck.
3. Open the JS console and observe the error message: [sprintf] unexpected placeholder
4. Try again but replacing "%.f" with "%.0f" in `https://fennel-lang.org/fennel/fennel.lua`, and observe that it now works.

As seen on the hell site: https://news.ycombinator.com/item?id=41484078
![Screenshot 2024-09-08 at 17-38-13 the Fennel programming language](https://github.com/user-attachments/assets/3d08870f-0569-45b4-bb5f-4b77e8e862c2)

My thoughts: This is probably caused by this bug: https://github.com/fengari-lua/fengari/issues/147 you can try to resolve that, or alternatively you can replace the instance (is it [this](https://github.com/bakpakin/Fennel/blob/869e75b4327de4345a00613443f7e6a559c86e58/src/fennel/view.fnl#L307)?) of "%.f" with "%.0f" or whatever.

**Comment by technomancy** [comment]
Thanks for letting us know! It says a lot about Fengari that we have been using it for so long without any trouble that we don't even bother to check compatibility upon a release nowadays.

I've turned the web repl back to 1.5.0 for now while we investigate the issue.

**Comment by samqiu** [comment]
[Dental_infection_simulating_skin_lesion.pdf](https://github.com/user-attachments/files/16927735/Dental_infection_simulating_skin_lesion.pdf)

**Comment by samqiu** [comment]
![kef-lsx-iis](https://github.com/user-attachments/assets/3ba613a1-cb59-49db-aa76-a57be9375c78)

**Comment by technomancy** [comment]
OK, I think I have a fix in 222e14c.
