### ISSUE TITLE
Able to use weapon after death

### ISSUE THREAD

**Issue by 44100hertz** [bakpakin/Fennel#486]
Oops! Maybe Let's disable input handling until the death screen appears.

**Comment by technomancy** [comment]
I don't think I can reproduce that one! =D

**Comment by rokf** [comment]
@44100hertz Haha, looks like the issue was meant for the https://github.com/bismuthsoft/super_rogue repository? 😄

**Comment by 44100hertz** [comment]
Yes it was. Sorry

**Comment by technomancy** [comment]
I love that yall are continuing working on that after the jam!

**Comment by jaawerth** [comment]
@44100hertz 
> Yes it was. Sorry

On the contrary, it brightened my day! It reminded me of the Dwarf Fortress Bugs bot account I used to follow when I was still on Twitter, which in turn led to the discovery that there's been one on fedi since 2022:

https://botsin.space/@dfbugs/113158738869661850
