### ISSUE TITLE
fennel repl support bracketed-paste

### ISSUE THREAD

**Issue by Freed-Wu** [bakpakin/Fennel#490]
https://github.com/ConradIrwin/vim-bracketed-paste
https://en.wikipedia.org/wiki/Bracketed-paste

> Bracketed paste (sometimes referred to as paste bracketing[1] ) is a mode of some terminal emulators which allows programs running in the terminal to treat pasted text differently from text typed normally

**Comment by technomancy** [comment]
Don't we get this for free thru our readline integration? As far as I can tell it already works.
