### ISSUE TITLE
"Base Library" of standard macros

### ISSUE THREAD

**Issue by thatismatt** [bakpakin/Fennel#55]
Is there any appetite for curating a few useful macros in to a standard module? (Not sure if this is really an "issue", but don't know where else to ask.)

I've taken the macros from `test-macros.fnl` and tweaked them slightly and also added thread last aka `->>`, and am finding them very productive.

I then wanted the correct syntax highlighting and indentation for `defn` so added it to @technomancy 's fennel-mode. And this got me thinking that a "standard" set of macros would be nice for tooling.

**Comment by bakpakin** [comment]
I do think at some point we need a standard macro library embedded in fennel for ease of use. A lot of macros from Common Lisp and Clojure core etc. would be very useful in nearly all fennel code (when-let, if-let, defn, defmacro, etc.).

I have just pushed an embedding of the 'defn' and threading macros that were previously in test-macros.fnl at the bottom of fennel.lua. Core macros should go in this embedded source. Feel free to add macros that you think are useful here and submit pull requests.

**Comment by thatismatt** [comment]
Super, I've just submitted a PR adding `->>`. I'm happy to close this issue now.

**Comment by technomancy** [comment]
I think there's room for more discussion around what kind of things ought to be included in such a standard lib; maybe we should keep it open. Personally I'm inclined to lean towards keeping the stuff that ships with fennel pretty minimal and letting macros mature in a separate library to let potential issues get sorted out before we commit to maintaining them as part of the language core.

**Comment by thatismatt** [comment]
I've just noticed that one of the changes that I had made in test-macros.fnl was to change `defn` from being global to local.

How would you feel about making that change too?
I've also create a PR for this (https://github.com/bakpakin/Fennel/pull/58), so feel free to continue the discussion there if that is more appropriate.

**Comment by technomancy** [comment]
I think `when`, `partial`, `:`, and maybe `lambda` can be ported over to macros without too much trouble once #59 is resolved.

The other candidates I can think of are `with-open` and `doto` from Clojure, but I'm not 100% convinced they're needed.

**Comment by technomancy** [comment]
I've ported `when`, `partial`, and `lambda` over to macros. (Brought the line count back down under 1300 briefly.) I'm not sure how to port `:` since it requires exposing `once` to the compiler environment, so I'm punting on that for now.

These macros all work fine with line numbering, but it may be worth noting that there doesn't seem to be a way for a macro to introduce a runtime `assert` which will have the line number of the calling code. Not sure how big of a problem that will be.

Are there any other macros worth considering for addition?

**Comment by thatismatt** [comment]
I think `case`, `some->` and `some->>` could be valuable. Perhaps `as->` too, in Clojure I use that less.

With regard to `some->`: I saw the discussion about `.?` (a nil shortcircuiting version of `.`), and thought that `(some-> obj (. :x) (. :y))` would be another way of providing that feature in a slightly more general way.

Also, how would people feel about extending `->` and `->>` to allow for "lone" symbols, i.e. `(-> v f)` and `(-> v (f))` would be equivalent.

**Comment by bb010g** [comment]
I'd be interested in a Racket-style `match` macro (to be ideally paired with `defn/match`), but it may be too large for what we'd like in a standard library.

If the compiler tracked basic binding data, then I think you could do `:` without exposing assert just by using `let`.

**Comment by technomancy** [comment]
I've got a pattern matching macro in #126. I would be up for adding an equivalent of `some->` as long as we can come up with a better name. Beyond that, maybe we should open separate issues for other macro suggestions rather than this vague one.

**Comment by thatismatt** [comment]
I agree, lets close this.

For an alternative name for `some->` how about `-?>` and `-?>>` read as "thread maybe" perhaps.

**Comment by technomancy** [comment]
Yeah, IMO those are better.
