### ISSUE TITLE
Locals don't work in REPL

### ISSUE THREAD

**Issue by divs1210** [bakpakin/Fennel#71]
Hi! Thank you for your great work on Fennel!
I'm facing an issue where locals don't seem to register in the repl:
```clojure
>> (local x 1)

>> x

>> (global x 1)

>> x
1
```
I'm on a Mac and installed via `brew`.
Thanks again! Can't wait to mess around with the LOVE engine!

**Comment by bakpakin** [comment]
This is the expected behavior. Locals work like they do in the Lua repl; each for in the repl is evaluated in its own chunk. To put multiple forms in the same chunk, wrap them in the `do` form.

```lisp
>> (do
  (local x 1)
  1)
1  
```

**Comment by divs1210** [comment]
Thank you for clarifying!
I'm from the `Clojure` world, and was expecting the repl to behave like it does there.

**Comment by technomancy** [comment]
We should explain this in the tutorial or something though, because it's annoying and very unexpected if you are new to lua.

**Comment by thatismatt** [comment]
How about introducing a `def` macro, that defaults to `local` in compiled fennel, but at the repl it does `global`. I'm imaging some compiler state that is toggled when starting the repl and accessible from this new `def` macro.

This is clearly a hack, but I think it could be really worthwhile. I would certainly find it convenient to ease working with top level variables at the repl.
