### ISSUE TITLE
Scripting Terra

### ISSUE THREAD

**Issue by yvendruscolo** [bakpakin/Fennel#75]
Is there a possibility for fennel to also work as an extension/scripter/metalang for [Terra](http://terralang.org/)? 

The only form/macro to be added would be `terra`, which works like `fn` or `defn`, the only complication being that it requires static types for the arguments of such function. 

This is the most basic example on Terra's page:

```lua
C = terralib.includec("stdio.h")
terra hello(argc : int, argv : &rawstring)
    C.printf("Hello, Terra!\n")
    return 0
end
```

Which I believe could be the result of calling something like this in fennel:

```
(global C (terralib.incudec "stdio.h"))
(global hello 
    (terra [[argc int] [argv &rawstring]] 
        (do (C.printf "Hello, Fennel!\n") 0)))
```

**Comment by bakpakin** [comment]
One would need to add a special form or use the eval-compiler statement, but yes it should be possible. The fn special for could certainly be modified, and the canonical code would look more like

```lua
(global C (terralib.incudec "stdio.h"))
(terra hello [[argc int] [argv &rawstring]] 
    (C.printf "Hello, Fennel!\n")
    0)
```
If you would be willing to take a stab at it and open a PR, I would gladly merge it, but if it is included it will only be enabled via an option/flag. I think an implementation should be possible in only ~50 more lines to the compiler, give or take (basically copying the code from the fn special and modify the emitted code to use terra instead on function, add types, etc.) Check line 1041 in fennel.lua for the relevant code.

**Comment by yvendruscolo** [comment]
I don’t think I know lua well enough to do it, but it’s a good chance/reason to learn more!

**Comment by thatismatt** [comment]
@yvendruscolo - FYI @BitPuffin has a fork, that I think is targetting Terra: https://github.com/BitPuffin/fying

**Comment by technomancy** [comment]
Sounds like this should probably be tracked elsewhere then?
