### ISSUE TITLE
Behavior of the Product Function (*)

### ISSUE THREAD

**Issue by omidmnz** [bakpakin/Fennel#76]
This might be a little bit of a minor complaint, but `(*)` returns 0 in Fennel, but it returns 1 in Scheme, Common Lisp, Emacs Lisp, Clojure, and every other Lisp I know of. And 1 is a more sensible answer in some sense, since `(+)` returns 0, which is the identity element for +, and the identity for * is 1.

However, this behaviour might be there for some compatibility issue with Lua. But even in that case,  I think it should be documented more explicitly.

P.S.: I didn't know what to tag this, that's why I didn't.

**Comment by bakpakin** [comment]
I agree, the normal lisp behavior is preferred. I have updated this in a new commit 0f23729. If you pull from master this should fix the problem.

**Comment by omidmnz** [comment]
This fixes the issue.
Thanks
