### ISSUE TITLE
Destructuring fn, each locals?

### ISSUE THREAD

**Issue by technomancy** [bakpakin/Fennel#85]
Right now destructuring only applies to `local`, `let`, `var`, `global`, and `set`. It would be convenient if locals introduced by `fn` could also have destructuring applied. @bakpakin is this something you were planning on implementing, or was there a reason to leave it out?

**Comment by bakpakin** [comment]
There's no reason to leave it out, its a very re I reasonable request. I simply forgot about it.

**Comment by technomancy** [comment]
Thanks for the confirmation. I figure we could also add it for `each` while we're at it.
