### ISSUE TITLE
support multiline string?

### ISSUE THREAD

**Issue by FongHou** [bakpakin/Fennel#87]
Hi,

Is it possible to support multiline string? It seems [[...]] can't be used for that anymore, use """ ... """ instead?

Thanks!

**Comment by uvtc** [comment]
Is there a reason why:

~~~
(var s "this is
a multi-line
string")
~~~

couldn't or shouldn't work?

**Comment by technomancy** [comment]
@uvtc we should add support for that to the compiler; I believe it is simply an oversight.

In the mean time, it works with backslashes:

```lisp
(var s "this is\
a multi-line\
string")
```

**Comment by bakpakin** [comment]
Good suggestion, just pushed an updated for this in commit 9f5c2808e1507c9d3d344900cf553b9ec8e0c08a. It was a very simple change to the parser.

**Comment by uvtc** [comment]
Cool!
