### ISSUE TITLE
In the tutorial, tables: how to push, pop, etc for sequential tables

### ISSUE THREAD

**Issue by uvtc** [bakpakin/Fennel#88]
In the tutorial, section "Ok, so how do you do things?" :: "Tables", there should be a section specifically for sequential tables, with info on how to do the following:

  * check if an item is present in the sequential table
  * get an item using its index
  * push/pop (to/from *end* of sequential table)
  * shift/unshift (to/from *front* of sequential table)
  * get an item's index using its value

**Comment by uvtc** [comment]
Got it. Thanks, Phil.

**Comment by technomancy** [comment]
In `lua-primer.md` it says

> In particular `table.insert` and `table.remove` are intended for
> sequential tables; they will shift over the indices of every element
> after the specified index. To remove something from a non-sequential
> table simply set the field to `nil`.

Do you think it would be enough to link this from the tutorial, or should it be expanded as well? Maybe framing it in terms of push/pop would be clearer.

**Comment by uvtc** [comment]
I think it's best to:

  * keep the paragraph in the lua-primer
  * plan to add more to the lua-primer anyway
  * to the tutorial add the block of examples. These will only take up a handful of lines but be very useful to new users reading the tutorial who haven't used Lua much if at all.

The block should probably come right after

    tbl) ; -> {"a long string" "the first value" 12 "the second one"}

and be something like:

~~~~~~
Accessing and mutating sequential tables:

~~~lisp
(local ltrs ["a" "b" "c" "d"])

;; Recall, indices start at 1.

(table.remove ltrs)       ; Removes "d"
(table.remove ltrs 1)     ; Removes "a"
(table.insert ltrs "d")   ; Appends "d"
(table.insert ltrs 1 "a") ; Prepends "a"

(. ltrs 2)                ; -> "b"
(lume.find ltrs "b")      ; -> 2

;; Print out the table:
(each [k v (ipairs ltrs)] (print k v))
~~~
~~~~~~
