### ISSUE TITLE
What is the use of `do local _ = <function-name> end`?

### ISSUE THREAD

**Issue by xvrdm** [bakpakin/Fennel#97]
Hi all and thanks to the contributors for this awesome project!

I tried to convert some [Hammerspoon](http://www.hammerspoon.org/) script to Fennel and noticed something strange in my compiled output. Why does each function I declare get an additional `do local _ = <function-name> end`?

From the issues I read, there seem to have been similar problems in the past but it looks like  they were fixed. https://github.com/bakpakin/Fennel/pull/6

So maybe it is done to my code... But after reading [this question on SO](https://stackoverflow.com/questions/23895406/why-use-a-do-end-block-in-lua#23899152), I really don't see why these `do end` would be useful (as they set a `local` that is never used).

**Fennel code:**

```
(fn appToggleScanSnap [data]
  (if (= data.eventType "added")
        (hs.application.launchOrFocus "ScanSnap Manager")
      (= data.eventType "removed")
        (let [app (hs.appfinder.appFromName "ScanSnap Manager")]
          (app.kill))))

(fn settingToggleKinesis [data]
  (if (= data.eventType "added")
        (when true
	  (hs.keycodes.setLayout "U.S. International - PC")
          (hs.execute "/Applications/Karabiner.app/Contents/Library/bin/karabiner select 1"))
      (= data.eventType "removed")
        (when true
          (hs.keycodes.setLayout "Swiss French")
          (hs.execute "/Applications/Karabiner.app/Contents/Library/bin/karabiner select 0"))))

(fn usbDeviceCallback [data]
  (if (= data.productName "ScanSnap S1300i")
        (appToggleScanSnap data)
      (= data.productName "Kinesis Keyboard Hub")
        (settingToggleKinesis data)))

(local usbWatcher (hs.usb.watcher.new usbDeviceCallback))
(usbWatcher.start)
```

**Compiled code:**

```lua
local function appToggleScanSnap(data)
  if (data.eventType == "added") then
    return hs.application.launchOrFocus("ScanSnap Manager")
  elseif (data.eventType == "removed") then
    local app = hs.appfinder.appFromName("ScanSnap Manager")
    return app.kill()
  end
end
do local _ = appToggleScanSnap end
local function settingToggleKinesis(data)
  if (data.eventType == "added") then
    if true then
      hs.keycodes.setLayout("U.S. International - PC")
      return hs.execute("/Applications/Karabiner.app/Contents/Library/bin/karabiner select 1")
    end
  elseif (data.eventType == "removed") then
    if true then
      hs.keycodes.setLayout("Swiss French")
      return hs.execute("/Applications/Karabiner.app/Contents/Library/bin/karabiner select 0")
    end
  end
end
do local _ = settingToggleKinesis end
local function usbDeviceCallback(data)
  if (data.productName == "ScanSnap S1300i") then
    return appToggleScanSnap(data)
  elseif (data.productName == "Kinesis Keyboard Hub") then
    return settingToggleKinesis(data)
  end
end
do local _ = usbDeviceCallback end
local usbWatcher = hs.usb.watcher.new(usbDeviceCallback)
return usbWatcher.start()
```

Question extra: When doing multiple actions as the result of a matched `if` condition, is it the best practice to use `let` (even without setting local variables)/`when` or is there another way (i.e. a `do` [a-la-clojure](https://clojuredocs.org/clojure.core/do))?

**Comment by bakpakin** [comment]
>  Why does each function I declare get an additional do local _ = <function-name> end?

As you may be able to guess, this bit of code does nothing but capture the side effects of whatever is right of the equals sign. This construct is emitted by the compiler when an expression that might have side effects is compiled but not used anywhere else. The assignment to the unused local is wrapped in a do ... end to further prevent extra leaking of side effects (the declaration of the _ local).

This is clearly unneeded in this case however, because the compiler was detecting that a simple function declaration might have side effects. This seems to be a regression in the compiler and I have pushed a  simple fix that will no longer emit the unnecessary assignment

> When doing multiple actions as the result of a matched if condition, is it the best practice to use let (even without setting local variables)/when or is there another way (i.e. a do a-la-clojure)

I would say when is the cleanest, but let may be good if you need intermediate values. As with clojure, a do works as well.

**Comment by xvrdm** [comment]
New ouput is clean! Thanks a lot!

```lua
local function appToggleScanSnap(data)
  if (data.eventType == "added") then
    return hs.application.launchOrFocus("ScanSnap Manager")
  elseif (data.eventType == "removed") then
    local app = hs.appfinder.appFromName("ScanSnap Manager")
    return app.kill()
  end
end
local function settingToggleKinesis(data)
  if (data.eventType == "added") then
    if true then
      hs.keycodes.setLayout("U.S. International - PC")
      return hs.execute("/Applications/Karabiner.app/Contents/Library/bin/karabiner select 1")
    end
  elseif (data.eventType == "removed") then
    if true then
      hs.keycodes.setLayout("Swiss French")
      return hs.execute("/Applications/Karabiner.app/Contents/Library/bin/karabiner select 0")
    end
  end
end
local function usbDeviceCallback(data)
  if (data.productName == "ScanSnap S1300i") then
    return appToggleScanSnap(data)
  elseif (data.productName == "Kinesis Keyboard Hub") then
    return settingToggleKinesis(data)
  end
end
local usbWatcher = hs.usb.watcher.new(usbDeviceCallback)
return usbWatcher.start()
```
